### ISSUE TITLE
Support multiple CRON expressions

### ISSUE THREAD

**Issue by Angrboda2** [opendistro-for-elasticsearch/alerting#100]
Complex schedules require more than 1 CRON expression, currently you can only enter 1 CRON expression. This forces you to create complex logic in painless scripting in triggers to create blackout windows which would be much better done using CRON.

**Comment by lucaswin-amzn** [comment]
Hi @Angrboda2, could you please share an example of using multiple cron expressions that can not be solved with a single one?
Thanks

**Comment by Angrboda2** [comment]
Yes I'm essentially trying to black out a maintenance window. Whatever
solution gets decided on I would not limit it to a single contiguous time
period. Often ad-hoc unexpected maintenance has to be done over multiple
days, or ongoing performance issues that take some time to solve, need to
be blacked out on irregular schedules.

Requiring scripting in the trigger (which I did successfully) is too much
work and it's not obvious on a surface level that there is logic "turning
it off".

Maybe I should  put in a separate request for this but a master blackout
option across all monitors is needed as well.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/47
