### ISSUE TITLE
Create Monitor throws 500 InternalServer Error

### ISSUE THREAD

**Issue by lvndc** [opendistro-for-elasticsearch/alerting#104]
On Alerting > Monitors> Create monitor, I can fill the form without a problem. However, hitting "Create" button doesn't do anything - there is a 500 InternalServer Error with message '[illegal_state_exception] settings.get("http.port") must not be null'

 - OS: Mac
 - Browser: Chrome
 - Elasticsearch + Kibana Version: 7.2.0

**Comment by tomerilp** [comment]
Any update on this?

**Comment by dbbaughe** [comment]
Hi @tomerilp,

Are you getting this error? For which version?

Thanks

**Comment by tomerilp** [comment]
@dbbaughe nvm, the branch I worked on wasn't updated for a long time
Thanks

**Comment by dbbaughe** [comment]
This should have been addressed as the http input commit was reverted.
