### ISSUE TITLE
Build package  

### ISSUE THREAD

**Issue by sc7565** [opendistro-for-elasticsearch/alerting#111]
How, do you execute build plugin? i.e wanted to generate package was not able to find a gradlew task or instructions

**Comment by sc7565** [comment]
Thanks @dbbaughe , I was able to execute above.. but still was not able to figure out where does this package is created - https://github.com/opendistro-for-elasticsearch/alerting/releases/download/v1.2.0.1/opendistro_alerting-1.2.0.1.zip

or may be I am not using proper package/publish command

**Comment by dbbaughe** [comment]
Hi @sc7565,

From the root directory of the project you should be able to find the zip in `./alerting/build/distributions`.

**Comment by sc7565** [comment]
Sorry to bug, you ./gradlew build does not produce any distributions can you let me know which gradle task or order of tasks to execute

**Comment by dbbaughe** [comment]
@sc7565,

`./gradlew build` should run all tests and build the zip
`./gradlew assemble` should just build the zip

Can you paste the results of the task? You might be looking in the wrong place still.
Could you try running `find . -name "*.zip"` from the ROOT directory of the project and paste the results.
And lastly if you still don't find anything, can you paste the contents of the build directory that you're looking in.

Thanks

**Comment by sc7565** [comment]
got the file, Thanks a lot
