### ISSUE TITLE
[BUG]Alert Plugin dose not work with xpack

### ISSUE THREAD

**Issue by lixunhuan** [opendistro-for-elasticsearch/alerting#115]
**Describe the bug**
Alert Plugin dose not work ,when I enable security module of xpack in version 7.2.0

**Additional context**
es-lin       | {"type": "deprecation", "timestamp": "2019-10-25T06:37:41,224+0000", "level": "WARN", "component": "o.e.d.s.a.b.h.DateHistogramAggregationBuilder", "cluster.name": "elasticsearch", "node.name": "7db618d1796d", "cluster.uuid": "lqMCwsozScu2k3ugIfvm3Q", "node.id": "o3B0XZPMQJGj7V8RsCduCA",  "message": "[interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future."  }
es-lin       | {"type": "server", "timestamp": "2019-10-25T06:37:41,225+0000", "level": "ERROR", "component": "c.a.o.a.MonitorRunner", "cluster.name": "elasticsearch", "node.name": "7db618d1796d", "cluster.uuid": "lqMCwsozScu2k3ugIfvm3Q", "node.id": "o3B0XZPMQJGj7V8RsCduCA",  "message": "Error loading alerts for monitor: _na_" ,
es-lin       | "stacktrace": ["org.elasticsearch.ElasticsearchSecurityException: action [indices:admin/exists] is unauthorized for user [_system]",
es-lin       | "at org.elasticsearch.xpack.core.security.support.Exceptions.authorizationError(Exceptions.java:34) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:576) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeSystemUser(AuthorizationService.java:378) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:183) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.authorizeRequest(SecurityActionFilter.java:172) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:158) ~[?:?]",
es-lin       | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$writeAuthToContext$24(AuthenticationService.java:563) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.writeAuthToContext(AuthenticationService.java:572) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$handleNullToken$18(AuthenticationService.java:465) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.handleNullToken(AuthenticationService.java:472) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.consumeToken(AuthenticationService.java:356) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$extractToken$9(AuthenticationService.java:327) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.extractToken(AuthenticationService.java:345) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$checkForApiKey$3(AuthenticationService.java:288) ~[?:?]",
es-lin       | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.xpack.security.authc.ApiKeyService.authenticateWithApiKeyIfPresent(ApiKeyService.java:360) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.checkForApiKey(AuthenticationService.java:269) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:252) ~[?:?]",
es-lin       | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.xpack.security.authc.TokenService.getAndValidateToken(TokenService.java:390) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:248) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$6(AuthenticationService.java:306) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:317) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:244) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:196) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:139) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:155) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:107) ~[?:?]",
es-lin       | "at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:143) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:121) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1214) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.exists(AbstractClient.java:1229) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.alerts.AlertIndices$createIndex$existsResponse$1.invoke(AlertIndices.kt:183) ~[opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.alerts.AlertIndices$createIndex$existsResponse$1.invoke(AlertIndices.kt:58) ~[opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.elasticapi.ElasticExtensionsKt.suspendUntil(ElasticExtensions.kt:142) ~[alerting-core-1.2.0.0.jar:?]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.alerts.AlertIndices.createIndex(AlertIndices.kt:182) ~[opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.alerts.AlertIndices.createIndex$default(AlertIndices.kt:178) ~[opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.alerts.AlertIndices.createOrUpdateAlertIndex(AlertIndices.kt:159) ~[opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.MonitorRunner.runMonitor(MonitorRunner.kt:184) [opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.resthandler.RestExecuteMonitorAction$prepareRequest$1$executeMonitor$1$1.invokeSuspend(RestExecuteMonitorAction.kt:71) [opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) [kotlin-stdlib-1.3.21.jar:1.3.21-release-158 (1.3.21)]",
kbn_s-lin    | {"type":"response","@timestamp":"2019-10-25T06:37:41Z","tags":[],"pid":1,"method":"post","statusCode":200,"req":{"url":"/api/alerting/monitors/_execute","method":"post","headers":{"host":"lll:5900","connection":"keep-alive","content-length":"1073","accept":"application/json, text/plain, */*","origin":"http://lll:5900","kbn-version":"7.2.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36","content-type":"application/json;charset=UTF-8","referer":"http://lll:5900/app/opendistro-alerting","accept-encoding":"gzip, deflate","accept-language":"en,zh;q=0.9,zh-CN;q=0.8,ko;q=0.7"},"remoteAddress":"10.116.12.84","userAgent":"10.116.12.84","referer":"http://lll:5900/app/opendistro-alerting"},"res":{"statusCode":200,"responseTime":25,"contentLength":9},"message":"POST /api/alerting/monitors/_execute 200 25ms - 9.0B"}
es-lin       | "at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]",
es-lin       | "at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]",
es-lin       | "at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]",
es-lin       | "at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]"] }
es-lin       | {"type": "server", "timestamp": "2019-10-25T06:37:41,225+0000", "level": "ERROR", "component": "c.a.o.a.MonitorRunner", "cluster.name": "elasticsearch", "node.name": "7db618d1796d", "cluster.uuid": "lqMCwsozScu2k3ugIfvm3Q", "node.id": "o3B0XZPMQJGj7V8RsCduCA",  "message": "Error loading alerts for monitor: _na_" ,
es-lin       | "stacktrace": ["org.elasticsearch.ElasticsearchSecurityException: action [indices:admin/exists] is unauthorized for user [_system]",
es-lin       | "at org.elasticsearch.xpack.core.security.support.Exceptions.authorizationError(Exceptions.java:34) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:576) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeSystemUser(AuthorizationService.java:378) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:183) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.authorizeRequest(SecurityActionFilter.java:172) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:158) ~[?:?]",
es-lin       | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$writeAuthToContext$24(AuthenticationService.java:563) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.writeAuthToContext(AuthenticationService.java:572) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$handleNullToken$18(AuthenticationService.java:465) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.handleNullToken(AuthenticationService.java:472) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.consumeToken(AuthenticationService.java:356) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$extractToken$9(AuthenticationService.java:327) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.extractToken(AuthenticationService.java:345) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$checkForApiKey$3(AuthenticationService.java:288) ~[?:?]",
es-lin       | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.xpack.security.authc.ApiKeyService.authenticateWithApiKeyIfPresent(ApiKeyService.java:360) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.checkForApiKey(AuthenticationService.java:269) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:252) ~[?:?]",
es-lin       | "at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.xpack.security.authc.TokenService.getAndValidateToken(TokenService.java:390) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:248) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$6(AuthenticationService.java:306) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:317) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:244) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:196) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:139) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:155) ~[?:?]",
es-lin       | "at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:107) ~[?:?]",
es-lin       | "at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:143) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:121) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1214) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.exists(AbstractClient.java:1229) ~[elasticsearch-7.2.0.jar:7.2.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.alerts.AlertIndices$createIndex$existsResponse$1.invoke(AlertIndices.kt:183) ~[opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.alerts.AlertIndices$createIndex$existsResponse$1.invoke(AlertIndices.kt:58) ~[opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.elasticapi.ElasticExtensionsKt.suspendUntil(ElasticExtensions.kt:142) ~[alerting-core-1.2.0.0.jar:?]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.alerts.AlertIndices.createIndex(AlertIndices.kt:182) ~[opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.alerts.AlertIndices.createIndex$default(AlertIndices.kt:178) ~[opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.alerts.AlertIndices.createOrUpdateAlertIndex(AlertIndices.kt:159) ~[opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.MonitorRunner.runMonitor(MonitorRunner.kt:184) [opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at com.amazon.opendistroforelasticsearch.alerting.resthandler.RestExecuteMonitorAction$prepareRequest$1$executeMonitor$1$1.invokeSuspend(RestExecuteMonitorAction.kt:71) [opendistro_alerting-1.2.0.0.jar:1.2.0.0]",
es-lin       | "at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32) [kotlin-stdlib-1.3.21.jar:1.3.21-release-158 (1.3.21)]",
es-lin       | "at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233) [kotlinx-coroutines-core-1.1.1.jar:?]",
es-lin       | "at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) [kotlinx-coroutines-core-1.1.1.jar:?]",
es-lin       | "at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) [kotlinx-coroutines-core-1.1.1.jar:?]",
es-lin       | "at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) [kotlinx-coroutines-core-1.1.1.jar:?]"] }

**Comment by f0xxx** [comment]
we have the same problem!

**Comment by robin-moser** [comment]
For reference: https://github.com/opendistro-for-elasticsearch/alerting/issues/94

The dev told they won't support X-pack security, so I really hope, someone of you guys have Kotlin/Java experience to commit to the project. I'm not experienced enough to archive it.

**Comment by aetter** [comment]
Hi @lixunhuan, a big part of why ODFE exists is our commitment to open source software, a distribution of Elasticsearch that anyone can use, modify, and redistribute. We don't test our plugins against proprietary X-Pack features and don't consider it a bug when they don't work together. Our focus is on building a richer open source Elasticsearch ecosystem.

**Comment by lixunhuan** [comment]
Found that ,every calling function of es-client ,must have a authentication object in threadlocal,helpful for passing though xpack-auth.

**Comment by aplsms** [comment]
did it fixed, or just closed?

**Comment by aplsms** [comment]
> Found that ,every calling function of es-client ,must have a authentication object in threadlocal,helpful for passing though xpack-auth.

@lixunhuan do you have it fixed?

**Comment by dominiclapointe** [comment]
And whay about https://www.elastic.co/what-is/open-x-pack

`The interaction model for open X-Pack will be identical to the open source Elastic Stack`

x-pack is open source (as elasticsearch is) and security is part of it. It seem more like a lock down user on opendistro... (by the way, security plugin for 7.2 is buggy as hell, lets say almost unusable, had to remove it and gowith x-pack)

What is the actual issue for adding a config that would let the dev select which 'elastic user' will run queries?

Thank you

**Comment by paramount2u** [comment]
any workaround on this issue ?

**Comment by gruselglatz** [comment]
Not a technical Problem. It seems to be a political problem from Amzn.
