### ISSUE TITLE
[BUG] Add ability to not rolloverHistoryIndex

### ISSUE THREAD

**Issue by lucaswin-amzn** [opendistro-for-elasticsearch/alerting#116]
**Describe the bug**
Even with disabling alerting / scheduled jobs the history index will be rolled over.

**To Reproduce**
1. Create a monitor and execute
2. Disable scheduled jobs

**New Expected behavior**
When disabling scheduled jobs history index should not be rolled over.

**Related Items:**
https://discuss.opendistrocommunity.dev/t/deleting-open-distro-alerting-from-kibana/1719/2

**Comment by skkosuri-amzn** [comment]
This is migrated by : https://github.com/opendistro-for-elasticsearch/alerting/pull/143
