### ISSUE TITLE
[BUG] Error when trigger condition compares with large number

### ISSUE THREAD

**Issue by bkmeneguello** [opendistro-for-elasticsearch/alerting#117]
**Describe the bug**
I'm trying to alert memory overuse from a Jenkins server running in Docker being monitored by metricbeats.
Since memory information is given in bytes, i need to compare it with a gigabytes number, but query fails above 2147483647 (MAX_INTEGER). See alert configuration in **attachment-1** and **attachment-2**.
The query works in elasticsearch, see **attachment-3**.

**To Reproduce**
1. Create alerts based on following attachements.
2. Observe the monitor bar in gray.

**Screenshots**
![Screenshot_2019-10-29 Kibana](https://user-images.githubusercontent.com/1322552/67803847-9a152600-fa6c-11e9-8769-20b1284b8663.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.1
 - Browser: Firefox
 - Version: 70.0

**Additional context**

**attachment-1**: Alert configuration
```json
{
  "search": {
    "indices": [
      "metricbeat-*"
    ],
    "query": {
      "size": 0,
      "query": {
        "bool": {
          "filter": [
            {
              "range": {
                "@timestamp": {
                  "from": "{{period_end}}||-15m",
                  "to": "{{period_end}}",
                  "include_lower": true,
                  "include_upper": true,
                  "format": "epoch_millis",
                  "boost": 1
                }
              }
            },
            {
              "match_phrase": {
                "container.name": {
                  "query": "jenkins",
                  "slop": 0,
                  "zero_terms_query": "NONE",
                  "boost": 1
                }
              }
            }
          ],
          "adjust_pure_negative": true,
          "boost": 1
        }
      },
      "aggregations": {
        "when": {
          "max": {
            "field": "docker.memory.stats.rss"
          }
        }
      }
    }
  }
}
```

**attachment-2**: Alert error history
```
{   "timestamp": 1572379041966,   "message": "Error evaluating trigger:\n... ggregations.when.value > 13500000000\n                             ^---- HERE" },
```

**attachment-3**: Working Query excerpt
```json
...
"query": {
    "bool": {
      "must": [
        {
          "match_phrase": {
            "container.name": {
              "query": "jenkins"
            }
          }
        },
        {
          "exists": {
            "field": "docker.memory.stats.rss"
          }
        },
        {
          "range": {
            "docker.memory.stats.rss": {
              "gte": 13500000000,
              "lt": null
            }
          }
        }
      ],
      "filter": [
        {
          "match_all": {}
        }
      ],
      "should": [],
      "must_not": []
    }
  }
...
```

**Comment by bkmeneguello** [comment]
@lucaswin-amzn this exact syntax didn't worked at first, but lead to a more intuitive error message: "Invalid int constant [13500000000]. If you want a long constant then change it to [13500000000L].", then I changed my expression  to `return ...aggregations.when.value > 13500000000L` and it worked.
I think the problem is with the error message, in this case.

Thanks for your support.

**Comment by lucaswin-amzn** [comment]
Glad the solution worked!
