### ISSUE TITLE
compatibility with elasticsearch 6.8.3

### ISSUE THREAD

**Issue by marwojt** [opendistro-for-elasticsearch/alerting#121]
Hello,
Please add support for elastic 6.8.3.
thank you

**Comment by dbbaughe** [comment]
Hi @marwojt,

We currently do not plan to support every patch version upgrade of elasticsearch versions. We did release support for one of the 6.8.x versions though. If you need a specific patch version you can change the version number in the build.gradle and build the alerting plugin.
