### ISSUE TITLE
Align monitor query with Kibana link

### ISSUE THREAD

**Issue by yissachar** [opendistro-for-elasticsearch/alerting#122]
As part of a trigger on a monitor I am trying to add a generated Kibana link that matches the query that triggered the alert. The problem that I am running into is that I can't get the Kibana link to align with the time period that the query ran over.

This is because the only dates that are available to us as far as I can tell are `{{periodStart}}` and `{{periodEnd}}`. `{{periodStart}}` seems to be when the monitor actually triggered, and `{{periodEnd}}` seems to be `{{periodStart}}` + the monitor interval (which is in the future). If I use these in the query e.g.: 

```
"from": "{{period_start}}",
"to": "{{period_end}}",
```
Then the monitor will never trigger since `{{period_end}}` is in the future. I am reduced to having to query:

```
"from": "{{period_start}}||-15m",
"to": "{{period_start}}",
```

Or:

```
"from": "now-15m",
"to": "now",
```

in order to get the monitor to trigger, but then I cannot build a suitable Kibana link since I only have `{{ctx.periodStart}}` being accurate, while I need some other variable that would give me the start time of the query which is 15 minutes prior. I would almost like `{{period_end}}` to mean the time that the alert was triggered `{{period_start}}` to mean `{{period_end}}` - the monitor interval, since then I would be able to achieve what I want to do.

(As a side note it is pretty confusing that we generally use `ctx.periodStart`, but in the query portion we use `period_start` instead. This is only mentioned offhand in https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/).

**Comment by dbbaughe** [comment]
Hi @yissachar,

The period_end should refer to the time your monitor is expected to run/execute. The period_start should be the period_end minus the interval. Are you running into a situation where the above is not true? If so could you give your version being used and example monitor so we can replicate.

**Comment by yissachar** [comment]
Hi @dbbaughe,

We're looking for something like what I think is described in #123 - a way to build a Kibana link automatically that corresponds to the query that triggered an alert so that a developer can quickly see what's going on. Since this feature doesn't yet exist we've tried to manually build this up ourselves.

When we create a monitor we add a range to the extraction query:

```
{
                    "range": {
                        "@timestamp": {
                            "from": "now-5m",
                            "to": "now",
                            "include_lower": true,
                            "include_upper": true,
                            "format": "epoch_millis",
                            "boost": 1
                        }
                    }
                }
```

We set the schedule to match this. We then create a trigger and add an action that will post to Slack. In the message we add a short description of the error and a Kibana link (generated by manually copying over the extraction query into Kibana, minus the range query). We then set the Kibana date filter using the mustache template:

```
{{ctx.results.0.hits.total}} bad thing(s) happened!

<our-domain.es.amazonaws.com/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'{{ctx.periodStart}}',mode:absolute,to:'{{ctx.periodEnd}}'))...<rest of the Kibana link>
```

This works fine most of the time. When an alert is triggered we get a Slack message with a nice formatted link that takes us to Kibana for the appropriate time period. But occasionally things don't quite line up. We'll get an alert that says:

```
1 bad thing(s) happened
```

but when we click the link we see that 2 bad things actually happened. Or vice versa, we get an alert that something happened but when clicking the link nothing shows up until we expand the date range manually.

Since the queries are identical between Kibana and the extraction query with only the date range differing, it seems like either there is a bug in how OpenDistro calculates dates or I am missing something about how the dates work.

**Comment by dbbaughe** [comment]
So one thing is if you have `"from": "now-5m", "to": "now"` in the query and you use periodStart/periodEnd in the Kibana URL that is indeed different. "now" refers to the actual now when the query is executed. So hypothetically if your monitor ran a few seconds late and in those few seconds you have an extra document that showed up in your results set and then you went to a Kibana link using periodStart/periodEnd then you would not see it. You also have the potential to miss a document since you're doing now-5m, if it ran a few seconds late and you're doing now-5m then you're missing a few seconds at the start too.

To clarify with an example - imagine you have a monitor that runs every 5 minutes and you created it at exactly 12:00:00PM which refers to HH:MM:SS:

You expect it to run at 12:05:00PM.
It actually was delayed by a few second, maybe JVM GC (long GCs could cause it to be quite a bit longer) or whatever caused a delay, regardless it can and will happen.
So let's say it runs at 12:05:37PM, i.e. 37 seconds late.

"now" = 12:05:37PM
"now-5m" = 12:00:37PM
periodEnd = 12:05:00PM
periodStart = 12:00:00PM

The periodStart/End will always be the theoretical period it "should" be running at with periodEnd being the execution time and periodStart being the beginning of the period (end minus interval).

**Comment by yissachar** [comment]
Thanks for the clear explanation, that all makes perfect sense. When I go back to what I tried when I first created this issue:
```
"from": "{{period_start}}",
"to": "{{period_end}}",
```

It all seems to work fine. I'm not sure what went wrong previously, but I'm just happy that it works now. Having a built in ctx Kibana URL would definitely be amazing, but at least now we should have something that reliably works. Thanks again!

**Comment by jackmagictavern** [comment]
HI @yissachar, we are building similar stuffs. (kibana links in alert so that engineer can click when alert happens) I'm trying to compose Kibana URL using 'ctx.monitor.inputs', bu the Kibana discover URL format seems not friendly at all. Could you give me an example on how you manage to do it?

> Hi @dbbaughe,
> 
> We're looking for something like what I think is described in #123 - a way to build a Kibana link automatically that corresponds to the query that triggered an alert so that a developer can quickly see what's going on. Since this feature doesn't yet exist we've tried to manually build this up ourselves.
> 
> When we create a monitor we add a range to the extraction query:
> 
> ```
> {
>                     "range": {
>                         "@timestamp": {
>                             "from": "now-5m",
>                             "to": "now",
>                             "include_lower": true,
>                             "include_upper": true,
>                             "format": "epoch_millis",
>                             "boost": 1
>                         }
>                     }
>                 }
> ```
> 
> We set the schedule to match this. We then create a trigger and add an action that will post to Slack. In the message we add a short description of the error and a Kibana link (generated by manually copying over the extraction query into Kibana, minus the range query). We then set the Kibana date filter using the mustache template:
> 
> ```
> {{ctx.results.0.hits.total}} bad thing(s) happened!
> 
> <our-domain.es.amazonaws.com/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'{{ctx.periodStart}}',mode:absolute,to:'{{ctx.periodEnd}}'))...<rest of the Kibana link>
> ```
> 
> This works fine most of the time. When an alert is triggered we get a Slack message with a nice formatted link that takes us to Kibana for the appropriate time period. But occasionally things don't quite line up. We'll get an alert that says:
> 
> ```
> 1 bad thing(s) happened
> ```
> 
> but when we click the link we see that 2 bad things actually happened. Or vice versa, we get an alert that something happened but when clicking the link nothing shows up until we expand the date range manually.
> 
> Since the queries are identical between Kibana and the extraction query with only the date range differing, it seems like either there is a bug in how OpenDistro calculates dates or I am missing something about how the dates work.

**Comment by smf-dgd** [comment]
@yissachar THANKS! This helped me out today!
