### ISSUE TITLE
Make original query parameters available in monitor templates

### ISSUE THREAD

**Issue by aetter** [opendistro-for-elasticsearch/alerting#123]
Originally reported as https://github.com/opendistro/for-elasticsearch/issues/46 by @gregsilin. Copy and pasting here.

---

We're deploying the opendistro elastic search plugin at our organization. Thanks for making it available!

Looking at the [available variables](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/#available-variables) section, there doesn't seem to be a way to reference elements of the original query programmatically. Ideally, we could include the URL for the extraction query or just the query itself, for example.

This would be very valuable, as it allows the engineer responding to quickly navigate to the problematic logs in Kibana.

We know we have the hits available through results, but in our case we'd have value in the original query instead.

Thanks for the consideration!

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/50
