### ISSUE TITLE
Compatibility with Elastic 7.4.2

### ISSUE THREAD

**Issue by jirisykora83** [opendistro-for-elasticsearch/alerting#126]
Hello!

Can you make the plugin compatible with Elasticsearch last 7.4.2?

thanks.

**Comment by nvgoldin** [comment]
Hey, anyone knows if this is under work?

**Comment by lucaswin-amzn** [comment]
Hi @nvgoldin and @jirisykora83, I am working on updating the plugin to 7.4.2, hope to something done soon!

**Comment by nvgoldin** [comment]
Great, thanks for the update!

**Comment by crtab** [comment]
Eagerly looking forward to this. Cheers.

**Comment by nvgoldin** [comment]
Amazing, thanks!

**Comment by nvgoldin** [comment]
@lucaswin-amzn - Any place we can download this version?
