### ISSUE TITLE
Alerting per documents/events

### ISSUE THREAD

**Issue by BlueRedTeam** [opendistro-for-elasticsearch/alerting#13]
Please add functionality to create alerts per document/events.
Ex: I have created virus detection alerts and Alert trigger for system xyx. Within 30 second another system abc got infected.mean virus detection events for system abc is there within 30 second of first alerts.but for second system alert is not getting trigger bcz first alerts active for one mn.
This is very big issue for security detection perspective

**Comment by elfisher** [comment]
Hi @BlueRedTeam, for your scenario you could do the following:

1. Define an index where each document represents a system
1. creating a monitor query which pulls systems (the documents in the index) that have viruses.
2. Set a trigger to alert if any documents are returned in the monitor. If any documents are retuned, it means at least 1 system has a virus.
3. Create an action which sends a notification with each system that has a virus. You could then investigate and address each system which has a virus.

Below is an example of how to extract each document and send in the action.

```
Monitor {{ctx.monitor.name}} is alerting. Please investigate the issue.
- Trigger: {{ctx.trigger.name}}
- Severity: {{ctx.trigger.severity}}
- Period start: {{ctx.periodStart}}
- Period end: {{ctx.periodEnd}}
 
Systems that have viruses:
{{#ctx.results.0.hits.hits}}
- Index: {{_index}}
- Document: {{_id}}
{{/ctx.results.0.hits.hits}}
```
The output of your alert would looks like
```
Monitor system virus detection is alerting. Please investigate the issue.
- Trigger: System Virus detection
- Severity: 1
- Period start: 2019-04-03T21:44:25Z
- Period end: 2019-04-05T21:45:25Z
 
Systems that have viruses:
- Index: logs-2015.05.18
- Document: oOco5WkBin_zcdI0gsBA
- Index: log-2015.05.18
- Document: oeco5WkBin_zcdI0gsBA
```
Using the webhook action type, you could tie the Alerting output in with a more comprehensive ticketing/event management system. It hadn't been our intent to try to recreate the functionality that exists in those types of systems. However we are welcome to hear thoughts on how you were planning on integrating the alerting tool and where you would like it to go.

**Comment by runarmyklebust** [comment]
Instead of creating specialized indices, you could do similar things with aggregations; ofc a bit depending on your data-structure.

E.g here is an example getting limited inodes pr system:

**Query-aggregation**
```
 "aggregations": {
        "instances": {
            "terms": {
                "field": "fields.instanceName",
                "size": 100,
                "min_doc_count": 1,
                "shard_min_doc_count": 0,
                "show_term_doc_count_error": false,
                "order": [
                    {
                        "_count": "desc"
                    },
                    {
                        "_key": "asc"
                    }
                ]
            },
            "aggregations": {
                "min_free_files": {
                    "max": {
                        "field": "system.filesystem.free_files"
                    }
                }
            }
        }
    }
```


**Condition:**
`ctx.results[0].aggregations.instances.buckets.size() > 0`

**Message**
```
Monitor {{ctx.monitor.name}} just entered alert status. Please investigate the issue.
- Trigger: {{ctx.trigger.name}}

- Disk free inodes < 100000 detected: 
{{#ctx.results.0.aggregations.instances.buckets}} 
  * {{key}} : ({{min_free_files.value}} free)
{{/ctx.results.0.aggregations.instances.buckets}}


```

**Comment by mgiammarco** [comment]
I have got the same problem.

**Comment by H1L021** [comment]
**Two approaches here :** 
1.  **Event Categorisation by Logstash** : Security systems like Antiviruses have high fidelity events by themselves meaning you would need very little correlation to trigger an alert if it was sent by Antivirus (same thing for EDR, WAF, etc...). So you can enrich your collected events at ingestion time using Logstash. For example, If event.name is "Virus Detected" then add field [event.type]=>alert and make your monitor filter for events coming from antivirus with event.type is alert in X minutes for the same hash value for example or file name. In my example you can basically still do the same thing with event.name field but hope you got the idea for more complicated correlation use cases. Use logstash as your first correlation/enrichment layer then opendistro monitors as a second one.

2. **Indexing alerts using Logstash** : If the first option is not applicable you can create a monitor that sends the alert to logstash instance via Webhook destination, have logstash listening on a specific port with a pipeline to process the alert JSON body and enrich it using personal fields like rule.name or alert.origin (like user.name if you wanna alert on users generating multiple alerts for example) etc. and then output back to elasticsearch under an alerts index like "alerts-opendistro-*" where you can use your own dashboards to visualize your alerts reports.

**Comment by qreshi** [comment]
Closing in favor of #326, please continue any further discussion there.
