### ISSUE TITLE
Does anyone have a webhook for smtp?

### ISSUE THREAD

**Issue by psyapathy** [opendistro-for-elasticsearch/alerting#139]
Hi all!

I understand that smtp alerting is still in development. Does anyone have a temporary solution as a webhook for this?

Thank you

**Comment by mihirsoni** [comment]
Duplicate #3 Tracking it there.

**Comment by lacksfish** [comment]
Possibly SendGrid, or Mailgun ?
Might not meet individual privacy requirements.
