### ISSUE TITLE
Compatibility with Elasticsearch 7.5.1

### ISSUE THREAD

**Issue by crtab** [opendistro-for-elasticsearch/alerting#140]
As 7.5.1 has been released, would be great to get support for it.

**Comment by tomerilp** [comment]
Also for 7.5.2 :)

**Comment by Ricaz** [comment]
It would be great if we could track progress somehow. Maybe a road map. Elasticsearch is on release 7.6.0 now. I'm waiting for a release for 7.5.0 to try the security plugin.

**Comment by dbbaughe** [comment]
We skipped 7.5 in favor of jumping to 7.6 and as of now it's unlikely we'll go back and release an official 7.5 version.
