### ISSUE TITLE
[BUG] Checkboxes to acknowledge alerts are all greyed out

### ISSUE THREAD

**Issue by userqth** [opendistro-for-elasticsearch/alerting#144]
**Describe the bug**
The checkboxes to acknowledge alerts are all greyed out. 

**Other plugins installed**
Using all the plugins that comes by default with OpenDistro 1.3.0 like the security plugin.

**To Reproduce**
1. Login to 'kibana' as admin user
2. Click on 'alerting'
3. All alerts are greyed out

**Expected behavior**
An alert should be checkable so that one can acknowledge it.

**Screenshots**
![image](https://user-images.githubusercontent.com/59957708/72515862-f3f9e080-3850-11ea-9a9c-5ed77018533e.png)

**Desktop (please complete the following information):**
 - OS: [MacOS Catalina 10.15.2]
 - Browser [Chrome 79.0.3945.117, Firefox 72.0.1]
 - OpenDistro 1.3.0. running in Docker

**Additional context**
Note that I am logged in as the build in admin user, which is not restricted so it doesn't seems to be a permissions problem.

**Comment by dbbaughe** [comment]
Hi @userqth,

Yes, only active alerts can be acknowledged since they are sending notifications.

Thanks,
Drew
