### ISSUE TITLE
Triggers generate unique alerts based on the value of a specified key 

### ISSUE THREAD

**Issue by michaelyatrakos** [opendistro-for-elasticsearch/alerting#145]
This feature request is similar to issue #13 however, I felt that the intentions of that issue were slightly different.

I have monitors that query memory, CPU, and filesystem statistics from a Metricbeat index along with triggers that generate alerts if certain usage statistics are over some threshold. The problem that I am facing is that there is no simple way to separate out which of my hosts are responsible for any alerts generated. For example, creating a simple visual graph monitor:

`WHEN average() OF system.memory.used.pct OVER all documents FOR THE LAST 5 minutes WHERE all fields are included`

and then defining triggers for some threshold value will generate an alert if **host A** violates that threshold, but will also generate an alert if **host A**, **B**, and **C** violate that same threshold with no visibility on what caused the alert.

There are two ways, that I am currently aware of, this issue can be circumvented but these also come with there own set of drawbacks. The naive approach would be to create monitors per host:

`WHEN average() OF system.memory.used.pct OVER all documents FOR THE LAST 5 minutes WHERE host.name is "host A"`

The other approach is to use an extraction query monitor that aggregates the results for each host:

```json
"aggregations": {
        "hosts": {
            "terms": {
                "field": "host.name",
                "size": 100,
                "min_doc_count": 1,
                "shard_min_doc_count": 0,
                "show_term_doc_count_error": false,
                "order": [
                    {
                        "_count": "desc"
                    },
                    {
                        "_key": "asc"
                    }
                ]
            },
            "aggregations": {
                "avg_mem_usage": {
                    "avg": {
                        "field": "system.memory.used.pct"
                    }
                }
            }
        }
    }
```
and then insert the host names into the action message:
```
Monitor {{ctx.monitor.name}} just entered alert status. Please investigate the issue.
- Trigger: {{ctx.trigger.name}}
- Severity: {{ctx.trigger.severity}}
- Hosts: 
{{#ctx.results.0.aggregations.hosts.buckets}}
     * {{key}} - {{avg_mem_usage.value}}
{{/ctx.results.0.aggregations.hosts.buckets}}
```
---
By allowing query results to be split based on a key and then running documents with unique values of that key through the trigger, you can generate alerts for each unique value. Something similar to the following:

`WHEN average() OF system.memory.used.pct OVER all documents FOR THE LAST 5 minutes WHERE all fields are included GROUP BY host.name`

where a trigger would then generate an alert for each unique hostname that violates the threshold.

**Comment by KennedyDeswal** [comment]
Hi @michaelyatrakos michaelyatrakos , 

I implemented the above and getting the mem utilization but its  coming like this - 0.5838038121 . How can I change it to percentage. Please suggest. I used the below.

- Hosts: 
{{#ctx.results.0.aggregations.hosts.buckets}}
     * {{key}} - {{avg_mem_usage.value}}
{{/ctx.results.0.aggregations.hosts.buckets}}

**Comment by qreshi** [comment]
Closing in favor of #326, please continue any further discussion there.
