### ISSUE TITLE
Support and evolution for elastic 6.8

### ISSUE THREAD

**Issue by piellick** [opendistro-for-elasticsearch/alerting#159]
Hello everyone,

i seem that alerting plugin have news releases and bug correction for Elastic 7.X . Have you plan to maintain a version with update / improvements for Elastic 6.8 ?

have a good day ! Great awork.

**Comment by dbbaughe** [comment]
Hi @piellick,

We currently do not have any plans to maintain an up to date 6.8 version of the plugin.
We do try to backport bug fixes where needed, but all future development is generally done on the master branch which represents the latest version we plan to support.

Thanks,
Drew

**Comment by celesteking** [comment]
But hasn't 6.8 branch stabilized and no more breaking changes happening to it? What's stopping you from autobuilding your stuff against latest ES releases? 

I see someone released v0.10.0.1 tag, but where are the binaries? I hate all this java crap.

**Comment by celesteking** [comment]
I need to install into an existing ES install.

**Comment by dbbaughe** [comment]
Hi @celesteking,

Unfortunately there are breaking changes between 6.x and 7.x versions. So the new changes that go into master are targeting 7.x which might have different interfaces and features used that are not available in 6.x. We will continue to support the 6.x branches with bug fixes and security fixes, but for the most part new features will only be targeting the latest version.

The v0.10.0.1 tag was a byproduct of publishing the notification sub-project jars to Maven for other plugins to use.

**Comment by celesteking** [comment]
I'm not asking for new features from master branch. I'm asking you to publish ES 6.8.8 compatible packages.  I've got an ES instance and I want to install your Alerting plugin. I can't find corresponding binary files of your plugin.  

Where are they? Why can't you make a dumpster where you would dump all binaries to? 

An example of good, proper dumpster: https://mirror.its.sfu.ca/mirror/CentOS/7/os/x86_64/Packages/
An example of bad, improper dumpster where you can't list what's inside: https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-security/

**Comment by celesteking** [comment]
```
-> Downloading https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-alerting/opendistro_alerting-0.10.0.0.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [opendistro_alerting] was built for Elasticsearch version 6.8.1 but version 6.8.8 is running
```

**Comment by dbbaughe** [comment]
Hi @celesteking,

As you probably saw from your latest comment there is a section in the documentation for installing the plugins individually here:
https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/

And as noticed these will only work for 6.8.1, we currently do not update every patch version for our plugins or ODFE, but it's something we can work on supporting. Feel free to raise a request in:
https://github.com/opendistro-for-elasticsearch/community/issues

You can definitely pull down the plugin and build your required version too to get it right now. You would need to change the Elasticsearch version here:
https://github.com/opendistro-for-elasticsearch/alerting/blob/opendistro-0.10/build.gradle#L20

This is assuming nothing breaks, which for patch level changes is usually always the case.

**Comment by celesteking** [comment]
I hate java. Thanks.

**Comment by celesteking** [comment]
I've built packages `opendistro for elasticsearch alerting` for version 6.8.8 and they appear to work, although I haven't tested that profoundly.
[opendistro-alerting-0.10.0.0-kibana.zip](https://github.com/opendistro-for-elasticsearch/alerting/files/4447131/opendistro-alerting-0.10.0.0-kibana.zip)
[opendistro_alerting-0.10.0.1-es.cek.zip](https://github.com/opendistro-for-elasticsearch/alerting/files/4447132/opendistro_alerting-0.10.0.1-es.cek.zip)
