### ISSUE TITLE
Alerting - monitors context.alert null or missing id

### ISSUE THREAD

**Issue by aradhell** [opendistro-for-elasticsearch/alerting#16]
Hello,

 First alert is coming with a null alert property, It is the first time I am using alerts but I guess it should be Active and has an id.

first alert
`"alert": null`

and then second one is missing the alert id.
`"alert":{
"state":"ACTIVE",
"error_message":null,
"acknowledged_time":null,
"last_notification_time":1553847937681
},`

I am trying to send an message with an alert id so I can use alert.id to automatically acknowledge this alert with an url in the first alert message.

Destination: Slack

Thanks in advance.

**Comment by dbbaughe** [comment]
Hi aradhell,

I'm assuming you have a monitor that has a trigger and an action with a slack destination (if wrong let me know!). When the trigger evaluates to true, you are sending the alert information to slack. The first time it is null, and the second time it has no alert id.

Currently the alert being provided to the trigger context and action context variables is the "current" alert that exists as the trigger is being evaluated (which is basically the previous alert if there is one). This is poor wording on our part, and we can look into providing both alerts.

Regarding the missing alert.id, could you provide what your action message looks like?

Thanks,
Drew

**Comment by aradhell** [comment]
Hi @dbbaughe 

You are right.

Please correct me if I am providing wrong message.

first alert message (ctx - context object)
```
array (
  'monitor' => 
  array (
    '_id' => 'qR_WxGkBTgUv7vc0rrKA',
    '_version' => 7,
    'name' => 'xx Critical',
    'enabled' => true,
  ),
  'trigger' => 
  array (
    'id' => '-h_cxGkBTgUv7vc0ibUf',
    'name' => 'xx critical trigger',
    'severity' => '1',
    'actions' => 
    array (
      0 => 
      array (
        'name' => 'Web Alert',
      ),
      1 => 
      array (
        'name' => 'notify slack xx critical channel',
      ),
    ),
  ),
  'results' => 
  array (),
  'periodStart' => '2019-03-29T10:04:37.564Z',
  'periodEnd' => '2019-03-29T10:05:37.564Z',
  'alert' => NULL,
  'error' => NULL,
)  
```
and the second one 

```
'monitor' => 
  array (
    '_id' => 'qR_WxGkBTgUv7vc0rrKA',
    '_version' => 7,
    'name' => 'xx Critical',
    'enabled' => true,
  ),
  'trigger' => 
  array (
    'id' => '-h_cxGkBTgUv7vc0ibUf',
    'name' => 'xx critical trigger',
    'severity' => '1',
    'actions' => 
    array (
      0 => 
      array (
        'name' => 'Web Alert',
      ),
      1 => 
      array (
        'name' => 'notify slack xx critical channel',
      ),
    ),
  ),
  'results' => 
  array (),
  'periodStart' => '2019-03-29T10:05:37.564Z',
  'periodEnd' => '2019-03-29T10:06:37.564Z',
  'alert' => 
  array (
    'state' => 'ACTIVE',
    'error_message' => NULL,
    'acknowledged_time' => NULL,
    'last_notification_time' => 1553853937999,
  ),
  'error' => NULL,
)
```

**Comment by dbbaughe** [comment]
Hi aradhell,

Thanks for finding this issue, it looks like we only bring back those values currently as noted [here](https://github.com/opendistro-for-elasticsearch/alerting/blob/master/alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/Alert.kt#L171).
I will make an issue to allow the full alert to be sent.
