### ISSUE TITLE
[BUG] swallowed mustache error

### ISSUE THREAD

**Issue by tjbaker** [opendistro-for-elasticsearch/alerting#160]
Using the following mustache template for alerting trigger messages:

```
Monitor "{{ctx.monitor.name}}" just entered alert state. Please investigate the issue!

- Trigger: {{ctx.trigger.name}}
- Severity: {{ctx.trigger.severity}}
- Period start: {{ctx.periodStart}}
- Period end: {{ctx.periodEnd}}
- Total Results: {{ctx.results.0.hits.total.value}}

First Result From Alert (1 of {{ctx.results.0.hits.total.value}} events):
{{#ctx.results.0.hits.hits.0}}
  Level : {{_source.level}}
  Logger: {{_source.logger}}
  Message: {{_source.message}}
{{/ctx.results.0.hits.hits.0}}
```

This code works well when the trigger fires and there are hits.
When I try to use the above and send a test message via the Kibana UI and there are no hits nothing happens, no messages are sent and there is no visible changes in the Kibana UI.  I see the following exception via developer tools:

```
action_results: {,…}
rgOS928B9DSJTFBIUlr3: {id: "rgOS928B9DSJTFBIUlr3", name: "sns", output: {}, throttled: false, executionTime: 1580414142870,…}
id: "rgOS928B9DSJTFBIUlr3"
name: "sns"
output: {}
throttled: false
executionTime: 1580414142870
error: "Error running com.github.mustachejava.codes.DefaultMustache@3236b9d7"
```

You can reference non-existing elements in the template and they're omitted from the output, but it seems that the template engine is not forgiving of missing "sections".  If you remove the {{#ctx.results.0.hits.hits.0}} block the test message with zero docs will succeed.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/53
