### ISSUE TITLE
How to include document fields in query to send them with alerts?

### ISSUE THREAD

**Issue by AndrewBoklashko** [opendistro-for-elasticsearch/alerting#166]
Hi, I am trying to setup alerting on errors in logs and I need to include the actual log messages in my alert action. I was researching logs for a couple of hours, but haven't found anything that could help me. Can I achieve it using this plugin?

I found an example of how to do this using Watcher: https://github.com/elastic/examples/tree/master/Alerting/Sample%20Watches/errors_in_logs
It would be very helpful if you could provide such examples for this plugin too.

**Comment by dbbaughe** [comment]
Hi @AndrewBoklashko,

Once you set up a monitor and trigger you can set up an action to send out a notification.
Inside the action message body you have access to a `ctx` variable which should have the results of that monitor's execution. I believe you can add `{{ctx.results}}` to the mustache template.

**Comment by AndrewBoklashko** [comment]
My mistake, I was setting `size` field in request to zero, so `hits` array was always empty.
Sorry for bothering.

**Comment by dhaulakhandi** [comment]
{{ctx.results}} gives me just [object Object] - how to get the values out of this?
