### ISSUE TITLE
Access restrictions for system variables  in Kibana Alerts

### ISSUE THREAD

**Issue by piano-antinomy** [opendistro-for-elasticsearch/alerting#168]
**Is your feature request related to a problem? Please describe.**
We use Kibana to provide visualization to customers for metrics stored in Elastic Search. Using Kibana monitor, customers can configure alerts and access some ctx variables like {{ctx.monitor}}, {{ctx.trigger}}, (all variables here https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/ ). We would like to restrict their access to those variables since those variables might contain some critical data in our use case. 

**Describe the solution you'd like**
It will be great if we can have the control of the visibility for those variables such that we can restrict users' access. 

**Describe alternatives you've considered**
If possible, we might want to do some "hack" in local and override the original Kibana/ES code. 

**Additional context**
None.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/54
