### ISSUE TITLE
Compatibility with Elastic 7.6.0

### ISSUE THREAD

**Issue by pbhalera** [opendistro-for-elasticsearch/alerting#170]
hello

Can you please add support to ES 7.6.0

Thanks

Regards
Parag

**Comment by kakoni** [comment]
This requires some work, as gradle needs to be updated to =>6.1

**Comment by dbbaughe** [comment]
Hi @pbhalera,

We have released support for 7.6.1.
If you specifically need 7.6.0 you'll need to pull down the opendistro-1.6 branch and change the elasticsearch version in the build.gradle to 7.6.0 and build the artifact. We currently target one patch version per minor version and do not release an alerting zip for every patch version. It's something we can possibly look into supporting in the future. For now though you would have to bump (or subtract) the patch version yourself and build.

**Comment by pbhalera** [comment]
Thanks
