### ISSUE TITLE
Exporting alerting objects

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/alerting#172]
Users would like to be able to export alerting objects (monitors, alerts, destinations) for importing into a different cluster

https://discuss.opendistrocommunity.dev/t/exporting-alerts/2081/5

**Comment by Kevc1** [comment]
Any updates on this ?
It is very time consuming and tedious to manually create 36 monitors and triggers from a Dev cluster to a PROD cluster.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/56
