### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by DILIPCHIRU** [opendistro-for-elasticsearch/alerting#177]

**Comment by DandyDeveloper** [comment]
@DILIPCHIRU Isn't this just a case of adding a aggregation on your query for the field in question and just use mustache templating to loop over the aggregation bucket?

**Comment by dbbaughe** [comment]
Hi @DILIPCHIRU,

For questions around using please post your questions on the forums here in the relevant forum: 
https://discuss.opendistrocommunity.dev/
