### ISSUE TITLE
[BUG][1.2.0] {{period_start}} and {{period_end}} returning "all shards failed" when clicking "Run" during monitor creation

### ISSUE THREAD

**Issue by DandyDeveloper** [opendistro-for-elasticsearch/alerting#181]
**Describe the bug**
This may be user error, but this has worked for me in the past. 

When creating a monitor in 1.2.0 I am trying to preview the results by clicking "Run", but the executed search term returns the following:

```json
{"ok":true,"resp":{"monitor_name":"Disk Checks","period_start":1584582619372,"period_end":1584600619372,"error":null,"input_results":{"results":[],"error":"all shards failed"},"trigger_results":{}}}
```
If you look at the epoch in the start and end date for this, they are off by a significant margin: 

```
dandy@DESKTOP:~$ date -d @1584582619372
Wed Jun  4 23:42:52 JST 52183
dandy@DESKTOP:~$ date -d @1584600619372
Tue Dec 30 07:42:52 JST 52183
```

These are the query conditions:

```json
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "@timestamp": {
                            "from": "{{period_start}}",
                            "to": "{{period_end}}",
                            "include_lower": true,
                            "include_upper": true,
                            "format": "strict_date_optional_time",
                            "boost": 1
                        }
                    }
                }
            ],
            "filter": [
                {
                    "bool": {
                        "should": [
                            {
                                "match_phrase": {
                                    "msg": {
                                        "query": "error",
                                        "slop": 0,
                                        "zero_terms_query": "NONE",
                                        "boost": 1
                                    }
                                }
                            }
                        ],
                        "adjust_pure_negative": true,
                        "minimum_should_match": "1",
                        "boost": 1
                    }
                }
            ],
            "adjust_pure_negative": true,
            "boost": 1
        }
    },
```
I can't figure out why this is happening but it seem to be consistent even after saving. 

**Other plugins installed**
Every plugin that comes with Opendistro ES. 

**To Reproduce**
1. Go to 'Alerting'
2. Create a new Monitor
3. Enter and interval and extractiong query
4. Enter a valid query that should return results, with the variables {{period_blah}} in the range
5. Hit run

**Expected behavior**
I'd expect the correct results and correct times to be passed into the query.

**Desktop (please complete the following information):**
 - OS: Windows 10 / Ubuntu 18
 - Browser [e.g. chrome, safari]: I've recreated this on the latest Chrome and Firefox

**Comment by DandyDeveloper** [comment]
I've upgraded to 1.4.0 and I'm still having this problem.

**Comment by dbbaughe** [comment]
Hi @DandyDeveloper,

The `period_start` and `period_end` are in `epoch_millis`. You are checking seconds with your `date` call which is why it's showing the year 52183 and incorrect month/day. Not sure what `strict_date_optional_time` is doing off the top of my head, but you could try changing it to `"format": "epoch_millis"`.

**Comment by DandyDeveloper** [comment]
@dbbaughe Thank you, this seems to be the problem. `strict_date_optional_time` seems to interpret differently. `epoch_millis` works as expected. 

I based my query from my visualizations, my mistake, I should be a little more careful on things like this. Thank you!
