### ISSUE TITLE
Destination support email

### ISSUE THREAD

**Issue by freegit9527** [opendistro-for-elasticsearch/alerting#182]
hi,
 We need to send an email for alert message，pls add this function.
thinks.

**Comment by DandyDeveloper** [comment]
https://github.com/opendistro-for-elasticsearch/alerting/issues/3

Literally the oldest request feature. It's almost finished. Please close.

**Comment by dbbaughe** [comment]
Closing in favor of #3.
I know there is a PR currently out from external contributor which we need to get someone to look over for review.
