### ISSUE TITLE
Limit false positives via "Pending" state with a configured threshold

### ISSUE THREAD

**Issue by nkhatwani-unicommerce** [opendistro-for-elasticsearch/alerting#193]
**Is your feature request related to a problem? Please describe.**
To avoid false alarms, the alarm should be raised only in case of trigger threshold is breaching for more than configured duration.

**Describe the solution you'd like**
If an alert rule has a configured threshold and the query violates the configured threshold it should first go to Pending instead of Active. Going to Pending, should not send any notifications. Once the alert rule has been firing for more than For duration, it will change to Active and send alert notifications.

**Additional context**
https://grafana.com/docs/grafana/latest/guides/whats-new-in-v5-4/#alerting

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/58
