### ISSUE TITLE
[BUG][QUESTION] How to work around JSON templating for Webhooks?

### ISSUE THREAD

**Issue by DandyDeveloper** [opendistro-for-elasticsearch/alerting#196]
I can't see a previous discussion on this, and I don't know how to workaround it. I don't consider this a bug in Open ES, but because of the inherent expectations for the recipients to receive JSON objects, how do we deal with this?

What do we do when dealing with JSON object on webhooks? Current templating with aggregations basically makes it impossible due to trailing commas. 

For example, using any kind of templating requires iterations over an object in the ES response object. However, every json iteration that will be separated by a comma will always have a trailing comma like so: 
```json
{
  "obj1": "val1",
  "obj2": "val2",
  "obj3": "val3",
  "obj4": "val4", <- Sadface
}
```

The vast majority of JSON compliant webhooks will reject this / fail to decode the JSON object on the other end. 

Any suggestions on how to get around this? 

Discussion here: https://discuss.opendistrocommunity.dev/t/mustache-template-function-removing-trailing-comma/2528

**Comment by DandyDeveloper** [comment]
@dbbaughe You've been super helpful recently. Wonder if you've got a suggestion for this? Could we have a trim function in ES that might check for this. 

Say if the header is present in webhook, run it through a validate function that will trim the object?

**Comment by DandyDeveloper** [comment]
https://discuss.opendistrocommunity.dev/t/mustache-template-function-removing-trailing-comma/2528/4

Discussion is ongoing here.

**Comment by samidhtalsania** [comment]
Ran into the same issue

**Comment by NicoP-S** [comment]
I have the same problem. At the moment I add an empty object after the iteration. On the Webhook side the empty object will be ignored.
A clean json would be better.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/59
