### ISSUE TITLE
Need an artifact for Elastic Search 7.6.2

### ISSUE THREAD

**Issue by Haneefh** [opendistro-for-elasticsearch/alerting#198]
Hi,
Can I get an open Distro Artifact for Elastic Search 7.6.2 along with the instructions please

**Comment by dbbaughe** [comment]
Hi @Haneefh,

You'll need to bump the elasticsearch version in the [gradle file here](https://github.com/opendistro-for-elasticsearch/alerting/blob/master/build.gradle#L20).
And then you can follow the build instructions on the README.
First follow the [SETUP instructions](https://github.com/opendistro-for-elasticsearch/alerting#setup) and then follow the [BUILD instructions](https://github.com/opendistro-for-elasticsearch/alerting#building-from-the-command-line).
This should produce a 7.6.2 artifact for you as long as the tests passed and nothing broke between 7.6.1 and 7.6.2.
We currently do not do one-off builds/upgrades for versions though as we follow the ODFE version.
