### ISSUE TITLE
[BUG] Disabled monitor is still running

### ISSUE THREAD

**Issue by lucasGras** [opendistro-for-elasticsearch/alerting#199]
I've created a monitor with the enabled property set to false, such as follow:

```
{
  type": "monitor",
  "schema_version": 1,
  "name": "monitor_23456",
  "enabled": false,
  "enabled_time": null,
  ...
}
```

I've set a short interval period to see if the monitor was still executing if the enabled field is set to false. And the monitor does execute, wich is, I guess, an error. A monitor with the enabled field set to false shouldn't be able to run.
Maybe this field is not for monitor enabling purpose, so what does it stand for ?

I'm using the latest Opendistro version with ES-oss 7.6.1, running it for development purpose on ubuntu.

Thanks,

**Comment by dbbaughe** [comment]
Hey @lucasGras,

Trying to replicate this, but not able to so far. You created this through Kibana or API? If API could you paste your response too and if through Kibana could you try through API and see if there's any difference to narrow it down. And when you say it still executes, what are you using for confirmation? It created an alert?

`enabled: false` should not be scheduling the monitor as you expected.

**Comment by lucasGras** [comment]
Thanks for your quick answer @dbbaughe !

I finally managed to make it works, it was a mistake from my side ! Close it down
