### ISSUE TITLE
New Maven Endpoint for ODFE

### ISSUE THREAD

**Issue by gaiksaya** [opendistro-for-elasticsearch/alerting#214]
Hi, 
The maven endpoint for ODFE has changed from https://oss.sonatype.org/service/local/staging/deploy/maven2 to **https://aws.oss.sonatype.org/service/local/staging/deploy/maven2**

The login credentials are the same as before. However, the user token has been updated. Infra team will updated the user token credentials (used in maven workflows). However, the URLs in the codebase needs to be updated by the plugin teams.

Currently, the old URL and user token is active. Infra team will update the token on 6/22. Make sure to update the URLs by then

More details: https://issues.sonatype.org/browse/OSSRH-47276

Thanks!

**Comment by dbbaughe** [comment]
https://github.com/opendistro-for-elasticsearch/alerting/blob/master/notification/build.gradle#L88
Merged
