### ISSUE TITLE
Run opendistro alerting plugin background jobs securely

### ISSUE THREAD

**Issue by skkosuri-amzn** [opendistro-for-elasticsearch/alerting#215]
#### Background
Also refer to issue (https://github.com/opendistro-for-elasticsearch/alerting/issues/6)
OpenDistro plugins have background jobs which run periodically, like alerting monitors. This issue explores approaches to securely run these jobs. 
_Consider below sample configuration:_
OpenDistro Roles : `ops_role`, `hr_role`
Mapping Role to Index :
-`ops_role` index_permissions has `app_logs_index`.  
-`hr_role`  index_permissions has `salaries_index`.
Users: `chip_user`,`dale_user`    
- `chip_user` is part of IT operations team and can access only `app_logs_index`, he is
    assigned `ops_role`.
- `dale_user` is part of HR department and can access only `salaries_index`, so he is assigned 
    `hr_role`.

#### Approaches:
**Option 1: ImpersonateUser**
1. Store the user who created the alerting monitor as part of the monitor configuration. 
1. When the alerting monitor runs, its assumes the user from monitor configuration and runs
the search. 
1. Alerting monitor created by `chip_user` can search only `app_logs_index` and 
can't search on `salaries_index`. Similarly, monitor created `dala_user` can't search `app_logs_index`.

**Pros:**
1. Access permissions for the user can be enforced both at monitor create time and monitor periodic runs.
1. If the user permissions change after monitor is created, this method handles it. For example: `chip_user` had `admin_role` when he created monitor and latter has only ops_role. 
1. We can configure to show only monitors, destinations, alerts for that user in kibana. And admin can see all monitors, destinations and alerts. 

**Cons:**
1. When a user leaves the organization, the monitor runs fail. Admin user has to 
explicitly move the monitors from `chip_user` to `mickey_new_user`.

**Option 2: RolesInject (a.k.a ImpersonateRole/AssumeRole)**
1. Store the opendistro roles of the user who created the alerting monitor as part of the monitor configuration. 
1. When the alerting monitor runs, its assumes all the roles from monitor configuration and runs the search. 
1. Alerting monitor created by `chip_user` can search only `app_logs_index`, since `chip_user` has `ops_role` when its created.

**Pros**
1. Solves the delete user issue from option#1. When `chip_user` leaves the organization, the monitor continues to run as long as the `ops_role` is present.

**Cons**
1. All the roles of the user who created monitor have to be stored as part of configuration.
1. Can't handle if user permissions change after the monitor is created. Handles only the role 
permissions changes. For example: `chip_user` had `admin_role` when he created monitor and latter has only `ops_role`. Monitor will continue to run with `admin_role`.
1. We can't configure to show only monitors created by user in kibana.

**Comment by smlx** [comment]
Option 2 definitely sounds better to me. Option 1 sounds much too fragile since users are likely to come and go, but roles will be more permanent.

**Comment by fbarbeira** [comment]
I agree with smlx. 

In our configuration most of the alerts are shared between users who are in the same department (role). If security are user-oriented we will be duplicating alerts. And looks like administration will be easier with alerts role-oriented.

**Comment by skkosuri-amzn** [comment]
Thanks. Tagging more folks to comment @fabiocorneti @contato318 @MedoDome @nborisenko

**Comment by MedoDome** [comment]
Hey hey, 

I agree with smlx and fbaberia. 

Monitors should be connected with roles because users are sharing data between each other inside groups/tenants.

If the user losses his role to his tenant/group, he/she should lose access to the created monitor.

**Comment by skkosuri-amzn** [comment]
Thanks for the feedback. Adding @dinusX @hardik-k-shah to this discussion.

**Comment by skkosuri-amzn** [comment]
@jimishs

**Comment by hardik-k-shah** [comment]
Option#2 makes more sense. As roles is the final entity who will provide authorization.  Additionally, in option#1 if user role gets changed, all his/her monitor will stop running. Lets say an example where chip move to another team and his role changed. Now all monitor configured by chip will suddenly stopped working (unless it is properly handled and moved/copied to some other user).  Option#2 gives protection against this. 

For option#2 Cons #1 and #3 can be fixed. 

1. All the roles of the user who created monitor have to be stored as part of configuration.

We can ask user explicitly, which role user want to create alert/monitor with. You can fetch all  available role (assigned to user through account API and show them in drop down on kibana. User can choose specific role to create a monitor. There is a dry run option to validate if monitor has required permission to run. 

3. We can't configure to show only monitors created by user in kibana. 
We can also store user who created monitors along with role.  User can be use to just filter all monitor created by given user to display/manage monitors in kibana. 


Additionally,  we can safely say `Impersonate Role` as `Assume Role` functionality. For this use case, as background job is running as super admin, we can say super admin always have permissions to assume any role and scope down the permissions. And this approach can be extended to any background job which is going to run as admin but need to scope down the permission to run as limited permission set.  
Additionally, `Assume Role` functionality can be extended for admin user as well which will help admin to dry run and validate permissions of any new role he/she is creating before assigning it to actual user. (or can be use for debugging purpose as well)

**Comment by hardik-k-shah** [comment]
@lucaswin-amzn  What are your thoughts?

**Comment by skkosuri-amzn** [comment]
@hardik-k-shah Thanks for the detailed comments.

------
On "asking user explicitly to select which role he wants to use to create alert monitor with". I see couple of challenges:
1. User have to be ware of the roles that are needed. Most of the cases, I see admin's are aware of roles and they assign roles to users. If user needs to select the role, we adding additional UX overhead?
2. Current API signatures have to be changed to take the selected roles. We are mixing security with business logic?
Perhaps, we can look into in the latter phase?
--------
Yes, agreed on the "super admin always have permissions to assume any role and scope down the permissions."

**Comment by mogul** [comment]
For (1) above I think the users who are that unsophisticated probably only have one role available. If there's only one role, then don't make it a drop-down select, just show that one role as unconfigurable in the form. That will make the UX relatively unchanged for them, in terms of the number of things they have to know/set in order to submit.

On (2) I don't understand the concern... Can you elaborate on how you think scoping alerts to roles would be conflating security and business?

**Comment by skkosuri-amzn** [comment]
@mogul Thanks for the comments.
For first phase, I am thinking - we will copy all the roles user has and save it. In second phase, provide UI to select/modify the roles.

**Comment by skkosuri-amzn** [comment]
FYI  @praveensameneni

**Comment by CarlMeadows** [comment]
Can we add this to the roadmap - which release is this planned to be available for the Alerting plug-in?

**Comment by skkosuri-amzn** [comment]
> Can we add this to the roadmap - which release is this planned to be available for the Alerting plug-in?

Sure. Will do.

**Comment by skkosuri-amzn** [comment]
Implemented in 1.11.

**Comment by skkosuri-amzn** [comment]
Hi all,
We are going to demo and discuss Alerting Security in coming ODFE Community meeting on 11/16/2020/
Invite: https://opendistro.github.io/for-elasticsearch/blog/meetings/2020/11/community-meeting-late-nov/

See you soon.
thanks
