### ISSUE TITLE
Allowing additional CA certificates in custom webhook destinations

### ISSUE THREAD

**Issue by srilumpa** [opendistro-for-elasticsearch/alerting#216]
**Is your feature request related to a problem? Please describe.**

I am trying to set up alerting destination to a custom webhook using HTTPS. Unfortunately, the destination is configured with a certificate signed by a custom CA and I am not able to include this CA's certificate in the validation chain.

The following error is log whenever the trigger quicks off:

```
[2020-06-18T10:28:40,326][ERROR][c.a.o.a.d.f.CustomWebhookDestinationFactory] [srv-ec4-03p.infra.dc2.intra] Exception publishing Message: DestinationType: CUSTOMWEBHOOK, DestinationName:tools-notify-uservice, Ur
l: https://my.web.service/notify, scheme: https, Host: , Port: -1, Path: null, Message: {"source":{"monitor_name":"My monitor"},"attachments": [{"t
itle": "0 alerts between 2020-06-18T07:28:38.842Z and 2020-06-18T08:28:38.842Z","fields": [{"title": "Hits","value": "0"}]}]}
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[?:?]
[snip]
```

**Describe the solution you'd like**

Have a way to include one or several certificate in OpenDistro's truststore or equivalent.

**Describe alternatives you've considered**

I included the CA's certificate in the Java default truststore but with no changes in the error.

**Comment by daskanu** [comment]
Hey srilumpa,

we faced the same issue and I could solve it by creating a truststore with our custom CA.
I then added the following ES_JAVA_OPTS and finally got the custom webhook working:
-Djavax.net.ssl.trustStore=<LINK_TO_TRUSTSTORE>
-Djavax.net.ssl.trustStorePassword=<TRUSTSTORE_PASSWORD>

I hope this could help you.

Greetings

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/65
