### ISSUE TITLE
Allow specifying period size seperately from interval.

### ISSUE THREAD

**Issue by shawnz** [opendistro-for-elasticsearch/alerting#224]
**Is your feature request related to a problem? Please describe.**

Currently, when defining a monitor, {{period_end}} is defined as the current time at monitor runtime, and {{period_start}} is defined as {{period_end}} minus the interval time.

However, usually I want the period to cover *more time* than the interval time. That way there's less chance for late messages to be missed if they come right around the end of an interval.

**Describe the solution you'd like**

It would be helpful to be able to define the period size separately from the interval size.

**Describe alternatives you've considered**

As a workaround, I could just specify {{period_end}}||-5m or similar in my extraction query rather than {{period_start}}. However it would be more useful if I could control the value of {{period_start}} in the monitor settings, that way I do not need to repeat the duration in multiple places.

Thanks for considering this idea.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/67
