### ISSUE TITLE
[BUG] Alerting not honouring PUT method

### ISSUE THREAD

**Issue by thenom** [opendistro-for-elasticsearch/alerting#228]
**Describe the bug**
Cannot PUT a new monitor with a specified ID for a non-existant monitor:
```
PUT _opendistro/_alerting/monitors/flibble
{
  "type": "monitor",
  "name": "flibble",
  "enabled": true,
  "schedule": {
    "period": {
      "interval": 10,
      "unit": "MINUTES"
    }
...
```
Results in:
```
{
  "Message" : "Monitor with flibble is not found"
} {
  "_index" : ".opendistro-alerting-config",
  "_type" : "_doc",
  "_id" : "flibble",
  "found" : false
}
```

Is there any reason for this as this means that a search is required before hand to find if it exists in the cluster and then to perform a second call (either POST or PUT) based on the results of the search.  I am just in the process of setting up OpenDistro so not sure if this issue appears elsewhere.

https://tools.ietf.org/html/rfc2616#section-9.6
> If the Request-URI does not point to an existing resource, and that URI is
   capable of being defined as a new resource by the requesting user
   agent, the origin server can create the resource with that URI.

If this method was allowed as stated then this would remove that extra step in automation and you could just overwrite the monitor.  I initially thought this might have been to inject the additional fields that appear in the monitor after the initial POST but this cant be the case because you still inject those fields during subsequent PUT operations when providing an existing _id.

Thanks,

**Comment by skkosuri-amzn** [comment]
Thanks for creating this issue. `PUT _opendistro/_alerting/monitors/{id}` : needs to create new monitor, if the given {id} is not present.

**Comment by aditjind** [comment]
Hi @thenom 

From [RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.4) 

> Proper interpretation of a PUT request presumes that the user agent knows which target resource is desired. **A service that selects a proper URI on behalf of the client, after receiving a state-changing request, SHOULD be implemented using the POST method rather than PUT. [...]**
> 

In the current implementation on creating a new monitor, an ID is generated by the server which is a part of the URI on the update request. 

Please refer to [this](https://stackoverflow.com/questions/56240547/should-http-put-create-a-resource-if-it-does-not-exist#:~:text=The%20PUT%20method%20requests%20that,under%20the%20supplied%20Request%2DURI.&text=If%20the%20Request%2DURI%20does,the%20resource%20with%20that%20URI.) for full explanation.

**Comment by aditjind** [comment]
Hi @thenom 

According to the latest [RFC7231](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.4), the PUT method definition states that:

`A service that selects a proper URI on behalf of the client, after receiving a state-changing request, SHOULD be implemented using the POST method rather than PUT.`

Since the ID for the monitors the plugin creates via POST method has the ID generated randomly (the document ID for the monitor document), we think this change would break the contract. 

Let me know your thoughts. 

[Reference](https://stackoverflow.com/questions/56240547/should-http-put-create-a-resource-if-it-does-not-exist#:~:text=The%20PUT%20method%20requests%20that,under%20the%20supplied%20Request%2DURI.&text=If%20the%20Request%2DURI%20does,the%20resource%20with%20that%20URI.)

**Comment by thenom** [comment]
Hi @aditjind 

I think thats fine if the service picks the ID on behalf of the client but in this case we dont have the option to supply the ID.  In my use case the monitor does not exist.  For automation purposes, to initially inject the monitor this means that the process we have cannot use a pre-defined ID for re-use later (which we do for nearly all other config PUT's via the elastic API).

As we cannot provide this ID as part of the URI means that any future updates for that monitor means wether an initial lookup first to try and find the service generated ID OR storing the ID elsewhere after the first insert.

Thanks,
Simon

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/69
