### ISSUE TITLE
Incomplete rest API

### ISSUE THREAD

**Issue by jgprogramming** [opendistro-for-elasticsearch/alerting#229]
Hi all,

We're setting up automated deployment of opendistro. As one of the last steps we need to create some alerting destinations, like slack or webhooks. Due to incomplete rest API it is pretty much impossible to do in automated way.

Alerting rest API only support those paths for destinations as far as I know:
POST _opendistro/_alerting/destinations
PUT _opendistro/_alerting/destinations/<destination-id>
DELETE _opendistro/_alerting/destinations/<destination-id>

Destination id is randomly generated and returned in POST response and as far as I know there is no other way to retrieve it based on name, type or anything. This is unacceptable in automated environment where the only thing that identifies this destination is a name.

I'd expect that there would be either 
* an endpoint that returns all destinations and allows filtering based on unique values (like name should be, it isn't for some reason)
* a way to specify destination id during creation .

This is especially big issue when creating actions via API, which expects destination_id but there's no real way to check what it is except during creation.

**Comment by skkosuri-amzn** [comment]
Thanks @jgprogramming for opening this issue. You are correct, currently we don't have an API to get destinations. For your use-case `GET /_alerting/destinations/` with filters will suffice?

**Comment by jgprogramming** [comment]
Hi @skkosuri-amzn , yes, extending API in this way would solve our use case. Thank you for quick response.

**Comment by skkosuri-amzn** [comment]
https://github.com/opendistro-for-elasticsearch/alerting/blob/master/alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/resthandler/RestGetDestinationsAction.kt

@jgprogramming We added `GET /_alerting/destinations/` api to 1.11 release.
