### ISSUE TITLE
Email alert no sending

### ISSUE THREAD

**Issue by elfisher** [opendistro-for-elasticsearch/alerting#24]
Moving to Alerting repo https://github.com/opendistro-for-elasticsearch/community/issues/41

@Andrew302 message below:

Hi

I try configurate Alerting Open Distro. the problem is when try configurate destinations Amazon SNS and the emails not sending. The problem is i need specific IAM role ARN and a specific SNS ARN Role?

thanks

**Comment by aetter** [comment]
Hi @Andrew302, can you clarify where you're accessing Kibana and how you're running Elasticsearch? Docker? RPM?

**Comment by Andrew302** [comment]
i access kibana to through URL in elasticsearch service AWS. Elasticsearch running in aws. No container, no RPM. the plugin was installed after an aws service update

**Comment by aetter** [comment]
Hi @Andrew302, we typically reserve these discussions for the open source version of the feature, but in broad strokes:

1. Make sure that you have an IAM role with the following permissions (at minimum):

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "sns:Publish",
            "Resource": "*"
        }
    ]
}
```

And the following trust relationship:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "es.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

2. Make sure you have an SNS topic with an email subscription. If you used your own email, you'll have to confirm the subscription before you'll receive email alerts.

3. Make sure the alert is actually entering active status.

I'm going to close this issue, but thanks for reaching out!

**Comment by prashanthm10** [comment]
Hi, 

I am still unable to integrate Alerting with SNS service. Is there any other way to send alerts in email
