### ISSUE TITLE
A better way to analyze the alerts history

### ISSUE THREAD

**Issue by shubhamc183** [opendistro-for-elasticsearch/alerting#242]
Right now all the COMPLETED alerts are stored under the index `.opendistro-alerting-alert-history-<date>`, https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/settings/#alerting-indices.

Alerts dashboard shows the historical alerts.

**When the number of alerts increases it becomes very hard to get a taste of what is happening. Also, users are not able to perform filtering on the basis of Monitor, Trigger, and Severity.**

![image](https://user-images.githubusercontent.com/15362871/90917141-e9fc1980-e3ff-11ea-97d9-1b99e614dc70.png)

I have made a Grafana dashboard to query this data and provide filters on the basis of Monitor, Trigger, and Severity.

Grafana Dashboard: [12875](https://grafana.com/grafana/dashboards/12875)
Github: https://github.com/shubhamc183/grafana-dashboards#open-distro-alerts-history

**Does it make sense to document the link somewhere in this repo so that it may help others?**

![image](https://user-images.githubusercontent.com/15362871/90918038-a0143300-e401-11ea-8fb7-402a90c7fe31.png)

**Comment by shubhamc183** [comment]
@skkosuri-amzn please have a look.

**Comment by skkosuri-amzn** [comment]
@shubhamc183 Looks great. Please note: as part of #6 changes,  direct access to `.opendistro-alerting-alert*` indices will be restricted.  After those changes `.opendistro-alerting-alert*` data can be accessed only through Alerting Plugin apis.

**Comment by shubhamc183** [comment]
Thanks a lot for pointing it.
