### ISSUE TITLE
Is there any way to add labels and trigger messge in .opendistro-alerting-alert-history index?

### ISSUE THREAD

**Issue by shubhamc183** [opendistro-for-elasticsearch/alerting#243]
[alert_history.message](https://github.com/opendistro-for-elasticsearch/alerting/blob/master/alerting/src/main/resources/com/amazon/opendistroforelasticsearch/alerting/alerts/alert_mapping.json#L67) field stores the error message while sending an alerts in .opendistro-alerting-alert-history index.

**Similarly, can we have a field where we can save the actual message sent by the trigger?** Maybe in `action_execution_results.action_message`.

Also, our aim is to filter these documents over Kibana or grafana on basis of labels like `team`, `customer_id`, etc.

Since saving labels is out of scope here.

We can save the in a raw string manner in trigger message and apply regex over them. Example

`CUSTOMER_ID:123;TEAM:analytics;Message:Error while parsing.....`

Can you please what should be the best solution for this?

EXAMPLE
```
{
  "_index": ".opendistro-alerting-alert-history-2020.07.16-000022",
  "_type": "_doc",
  "_id": "-G9CFnQBtM8v9hK7IaXY",
  "_version": 1,
  "_score": null,
  "_routing": "XXXXXXXXXXXXX",
  "_source": {
    "monitor_id": "XXXXXXXXXXXXX",
    "schema_version": 1,
    "monitor_version": 9,
    "monitor_name": "XXXXXXXXXXXXX",
    "trigger_id": "XXXXXXXXXXXXX",
    "trigger_name": "XXXXXXXXXXXXX",
    "state": "COMPLETED",
    "error_message": null,
    "alert_history": [
      {
        "timestamp": 1598101266903,
        "message": "Error running action:\njava.net.SocketTimeoutException: Read timed out"
      }
    ],
    "severity": "1",
    "action_execution_results": [
      {
        "action_id": "RKs14nMBNAVh57Muyl_H",
        "last_execution_time": 1598101266807,
        "throttled_count": 0
      }
    ],
    "start_time": 1598101266807,
    "last_notification_time": 1598101266807,
    "end_time": 1598101516547,
    "acknowledged_time": null
  },
  "fields": {
    "last_notification_time": [
      "2020-08-22T13:01:06.807Z"
    ],
    "start_time": [
      "2020-08-22T13:01:06.807Z"
    ],
    "end_time": [
      "2020-08-22T13:05:16.547Z"
    ]
  },
  "sort": [
    1598101266807
  ]
}
```

**Comment by shubhamc183** [comment]
Is there any index that stores trigger messages?

Also, I wanted to open this issue as "enhancement" but got opened as "bug" please change it.

**Comment by skkosuri-amzn** [comment]
Thanks @shubhamc183. Will check this. Changed this to enhancement as you requested.

**Comment by shubhamc183** [comment]
@skkosuri-amzn any update on this? TIA

**Comment by shubhamc183** [comment]
@skkosuri-amzn is this on the wishlist of the project?

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/70
