### ISSUE TITLE
Ability to iterate over the list of hits, and send alert with multiple values

### ISSUE THREAD

**Issue by vinaymorkar** [opendistro-for-elasticsearch/alerting#267]
**Problem:**
I have multiple servers with metricbeat running on each of them. All the servers push the metric data on one index. Now if more than one servers exceed the set threshold I should get an alert with the name of the servers and the values they breached.

**Solution I would like to have**
There should be a way to iterate over the hits and create a map with key-value pairs that will contain the name and values of the servers and their breached values. Then i should be able to store this map in a variable that can be passed in the alert message.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/75
