### ISSUE TITLE
[BUG] Monitor select drop down and visual graph query not working properly with security

### ISSUE THREAD

**Issue by marin-packetai** [opendistro-for-elasticsearch/alerting#271]
**Describe the bug**
Define monitor Index select drop down not working as expected, the auto suggest options works only when more than 10 characters are entered throwing a security error otherwise.
After the selection of the index is successful the visual graph monitor query throws unexpected security errors.

**Other plugins installed**
Security plugin

**To Reproduce**
1. Go to alerting
2. Click on create monitor
3. Scroll down to define monitor and select visual graph
4. Start writing in the select indices drop down
5. Auto suggest option works only after more than 10 characters
6. After the index is selected select the time field
7. Try creating a monitor on the visual graph throws security errors even with proper permissions

**Expected behavior**
Auto suggest works on less characters not giving the false impression the indices are not available. 
The visual graph query works for the selected indices.

**Screenshots**
10 or less characters entered:
![Screenshot (1)](https://user-images.githubusercontent.com/72936455/96238248-90970d80-0f9e-11eb-9161-1ceab3cb436b.png)

More than 10 characters entered:
![Screenshot (2)](https://user-images.githubusercontent.com/72936455/96238370-b0c6cc80-0f9e-11eb-9c2f-16d2a07a4203.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
There could be issues with the security plugin because the responses from the API return permission errors.
On the index select it throws these error for less than 11 characters and the auto suggest is not successful:
- `https://kb.packetai.co:5601/api/alerting/_indices` endpoint returns `no permissions for [indices:monitor/settings/get]` even if the user has that(and even unlimited) permission to the targeted index pattern (and unlimited cluster permission).
- `https://kb.packetai.co:5601/api/alerting/aliases` endpoint returns `no permissions for [indices:admin/aliases/get]` even if the user has that(and even unlimited) permission to the targeted index pattern (and unlimited cluster permission).

For the visual graph query:
- ` https://kb.packetai.co:5601/api/alerting/monitors/_execute` endpoint returns `no permissions for [indices:admin/exists]` even if the user has that(and even unlimited) permission to the targeted index pattern (and unlimited cluster permission).

The only way these are resolved is by extending the targeted index pattern to `*` .

**Comment by skkosuri-amzn** [comment]
@marin-packetai I am not able to reproduce this. Auto suggest is working for me. What permissions you have for the user? and also please let us know the version of opendistro-elasticsearch.
