### ISSUE TITLE
Resolution Alert

### ISSUE THREAD

**Issue by shaikmuzakkir** [opendistro-for-elasticsearch/alerting#277]
**Is your feature request related to a problem? Please describe.**
I would like to have a feature wherein we receive slack notifications when there is a resolution of alert.

**Describe the solution you'd like**
If there is a live alert and if it gets resolved, would like to receive a notification that the alert is resolved.

**Comment by skkosuri-amzn** [comment]
This change is tracked in https://github.com/opendistro-for-elasticsearch/alerting/issues/169
