### ISSUE TITLE
allow to trigger an action if monitor changes to green

### ISSUE THREAD

**Issue by jannishuebl** [opendistro-for-elasticsearch/alerting#28]
Hi, 

we are looking for a new alerting system and we are wondering if it is possible to trigger an action when the monitor changes from the "error" state back to "normal" state?

It is a good automated feedback for all in the team that a problem is fixed again. 

What do you think about this? Or am I missing something and it is already possible to do this kind of alerts?

**Comment by dbbaughe** [comment]
Hi @jannishuebl,

Just to clarify, are you talking about when the alert goes from **active** to **completed** or **error** to **completed**?  The error state is supposed to represent something wrong with the query, trigger, or some other configuration, but not necessarily your data that you are alerting off of. Technically an alert would be able to go from **active** -> **error** -> **active** too.

Currently we do not support notifications of an alert being **completed**,  although I suppose you could create another monitor to monitor the **completed** alerts and alert whenever there is a new one. This seems like a temporary solution until we can figure out a better way to do this though.

Thanks for the feedback!

**Comment by jannishuebl** [comment]
Hi @dbbaughe ,

sorry for this unclear formulation, I am indeed talking about **active** to **completed** in the first place.
But I could also imagine **error** to **completed** but not in first place. The  **active** to **completed**  is more imported

**Comment by elfisher** [comment]
@dbbaughe and @jannishuebl I could also see one for **active** to **acknowledge** so that folks know someone is working the alert. Thoughts?

**Comment by dbbaughe** [comment]
@elfisher 
Seems like we could just make it generic and give the option of sending a notification whenever the alert state changes and let the user choose which state changes they are interested in being notified about. And to get more advanced maybe even the transitions between alert states, e.g. I don't want to be notified about an alert going from **completed** to **deleted**, but I do want to be notified about an alert going from **active** to **deleted**.

**Comment by elfisher** [comment]
@dbbaughe that makes a lot of sense. Generic state change notifications where users could define which state changes they want to alert on.

**Comment by vinooamzn** [comment]
@dbbaughe Would this choice happen in the trigger or in the action script?

**Comment by rhyscooper** [comment]
Notifications on any state change would be very useful. I can see scenarios where for a short alert, it could well have resolved before anyone gets to investigating it, and having a notification to inform that it's no longer an issue would be great.

**Comment by BDeus** [comment]
I agree, many monitoring system raise an event on status change and not only on error state.
It could be very usefull to implement this feature.

**Comment by rhyscooper** [comment]
Is there any chance this might get implemented? We want to push alert notifications into pagerduty to notify on-call technicians when issues arise (high cpu, high error rates etc, however if the issue resolves itself before it's acknowledged, it would be really useful to notify pagerduty so that the on-call tech no longer needs to respond.

We do have a sort of workaround where we can setup 2 triggers which trigger on opposite events (e.g. one for "high cpu", one for "not high cpu"), however it means we always have open active alerts which isn't clear to users in the alerting dashboard.

**Comment by AdrienKuhn** [comment]
We have the exact same situation.
We are also using PagerDuty and we are looking for a way to automatically resolve PagerDuty incidents when alerts are "Completed".

**Comment by luiscarbajo23** [comment]
Any news on this?

**Comment by franco-martin** [comment]
I love the idea of alerting on state change, as a workaround for alerts, you could setup two filters in the alert that use the @timestamp field to have the state of the alert 10 mins ago, and 5 mins ago.  Something like I explain [here](https://medium.com/deep-dive-into-elk/monitoring-changes-in-metrics-61fce4f8de07). 
lets say you are monitoring cluster state, from 7.00 to 7.05 you had 5 yellow status events and now from 7.05 to 7.10 you had 0. That would represent a completed alarm.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/31
