### ISSUE TITLE
Support changing timezone in notification message

### ISSUE THREAD

**Issue by joyyir** [opendistro-for-elasticsearch/alerting#285]
Notification message format can be specified using Mustache templates like below.
```
- Period start: {{ctx.periodStart}}
- Period end: {{ctx.periodEnd}}
```
Actual message looks like this. It uses UTC+0 time.
```
- Period start: 2020-10-24T10:56:43.738Z
- Period end: 2020-10-24T10:57:43.738Z
```

It is possible to misunderstand actual time because the most people live in different timezone.
So I think it will be good if changing timezone is possible.
Thank you.

**Comment by marshell0** [comment]
TriggerExecutionContext.kt
in constructor
change:
                 monitorRunResult.periodStart
                 monitorRunResult.periodEnd
to:
                 monitorRunResult.periodStart.atZone(ZoneId.systemDefault()).toLocalDateTime().toInstant(ZoneOffset.UTC),
                 monitorRunResult.periodEnd.atZone(ZoneId.systemDefault()).toLocalDateTime().toInstant(ZoneOffset.UTC),
resolve your problem

**Comment by seriouz** [comment]
Noticed this too, in MS Teams.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/76
