### ISSUE TITLE
[BUG] monitors are not available after upgrade to ODFE 1.10.1

### ISSUE THREAD

**Issue by arnitolog** [opendistro-for-elasticsearch/alerting#287]
**Describe the bug**
After upgrade to ODFE 1.10.1 users began to see "There are no existing monitors. Create a monitor to add triggers and actions." on Monitors page. 
In the browser on dev tools I see the following error:
[security_exception] no permissions for [cluster:admin/alerting/monitor/search] and User [name=kibana-test, backend_roles=[Logging-User], requestedTenant=null]
At the same time there is no possibility to add such permission in security plugin
Destination and Dashboard pages works fine

**Other plugins installed**
Security plugin.

**To Reproduce**
1. log in as non admin user
2. go to Alerting/Monitors
3. Page will show "There are no existing monitors. Create a monitor to add triggers and actions."
4. Error in the browser dev tools: "[security_exception] no permissions for [cluster:admin/alerting/monitor/search] and User [name=kibana-test, backend_roles=[Logging-User], requestedTenant=null]"

**Expected behavior**
The page should show a list of Monitors 

**Screenshots**
![image](https://user-images.githubusercontent.com/34036079/97280622-3111eb00-1845-11eb-9e8d-d5c582cff4bf.png)

**Desktop (please complete the following information):**
 - Browser chrome, safari
 - Version ODFE 1.10.1

**Comment by skkosuri-amzn** [comment]
Till [1.10.x](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/) Alerting supports `admin` user only. 
Could you please add `cluster:admin/alerting/*` to your role and check it. Security UI supports adding free text to the `Role` in advanced actions.

**Comment by arnitolog** [comment]
@skkosuri-amzn but the problem that there is no advanced section in the role in ODFE 1.10.x security plugin:
![image](https://user-images.githubusercontent.com/34036079/97326486-b82e8580-187c-11eb-9b26-543ce70c2b40.png)

**Comment by skkosuri-amzn** [comment]
Looks like you are seeing this issue with Security UI: https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/530

**Comment by skkosuri-amzn** [comment]
You could you API to add actions to the role like below reference example:
```
curl -XPUT -u  admin:admin --insecure https://localhost:9200/_opendistro/_security/api/roles/hr_role -H 'Content-Type:application/json' -d'{                                  
"cluster_permissions": [
"cluster:admin/alerting/*"
],
"index_permissions": [
{
"index_patterns": [
"hr_data"
],
"dls": "",
"fls": [],
"masked_fields": [],
"allowed_actions": [
"crud"
]
}
],
"tenant_permissions": []
}'
```

**Comment by arnitolog** [comment]
@skkosuri-amzn will try, thanks a lot.

**Comment by skkosuri-amzn** [comment]
@arnitolog Sure. Please let us know.

**Comment by arnitolog** [comment]
@skkosuri-amzn it works, thanks a lot.
