### ISSUE TITLE
[BUG] Data in the ".opendistro-alerting-alert*" index pattern is not displayed.

### ISSUE THREAD

**Issue by leejongpyo** [opendistro-for-elasticsearch/alerting#294]
**Describe the bug**

Data in the `.opendistro-alerting-alert*` index pattern is not displayed.
The index pattern is registered normally, but the data is not displayed.
We use the index pattern to visualize, but nothing is displayed.
How do I use the `.opendistro-alerting-alert**` index pattern?
Is there another way?

**To Reproduce**
1. Go to `Stack Management`
2. Click on `Index Patterns`  and `Create index pattern` 
3. Click on `Include system and hidden indices` and  Create index pattern `.opendistro-alerting-alert*` 
3. Go to `Discover`
4. Click on `.opendistro-alerting-alert*` indices
5. See "No results match your search criteria"

**Expected behavior**
View results match 

**Screenshots**
1. Create index pattern - `.opendistro-alerting-alert*`
![image](https://user-images.githubusercontent.com/40311906/98495551-b902e680-2282-11eb-93e4-2d085e927ac6.png)  

![image](https://user-images.githubusercontent.com/40311906/98495591-d46df180-2282-11eb-8ccb-b5cd166433b0.png)

2. Go to `Discover` and select `.opendistro-alerting-alert*` indices  
![image](https://user-images.githubusercontent.com/40311906/98495746-3a5a7900-2283-11eb-8381-5aad36d33a9c.png)  

3. Not displayed data   
![image](https://user-images.githubusercontent.com/40311906/98495785-4c3c1c00-2283-11eb-8ea0-2c68a2163dfd.png)

**Desktop (please complete the following information):**
 - OS: 
   - Server : Ubuntu 18.04  
   - Client : windows 10 
 - Browser : Crome, Firefox 
 - Version : 
    - Chrome : 86.0.4240.183
    - Firefox : 82.0.2 (64-bit)
    - Opendistro for Elasticsearch, Kibana: 1.11.0  (Docker)

**Comment by skkosuri-amzn** [comment]
@leejongpyo as part of #6 ,  starting 1.11.0 version `.opendistro-alerting-alert*` are configured as `opendistro-system-indices`  and direct access is restricted to super-admin/adminDN users only. 

Users can access alerts through the Alerting REST API  `/_opendistro/_alerting/monitors/alerts`.
If you dont want this additional level of security access control, you can remove `.opendistro-alerting-alert*` from the `opendistro-system-indices` entry in `elasticsearch.yml`

**Comment by leejongpyo** [comment]
@skkosuri-amzn 
Thanks for your answer
I modified `elasticsearch.yml` to access the `.opendistro-alerting-alert*` index pattern, and I solved the problem.
Thank you very much. :)
