### ISSUE TITLE
[BUG] Mustache template is invalid in the API

### ISSUE THREAD

**Issue by franco-martin** [opendistro-for-elasticsearch/alerting#296]
**Describe the bug**
When trying to upload a monitor that has "complex" mustache code  through the API I get a JSON error. 
**Other plugins installed**
None

**To Reproduce**
Code to use as request body 
`{
    "type" : "monitor",
    "schema_version" : 1,
    "name" : "server-uptime",
    "enabled" : false,
    "enabled_time" : null,
    "schedule" : {
      "period" : {
        "interval" : 1,
        "unit" : "MINUTES"
      }
    },
    "inputs" : [
      {
        "search" : {
          "indices" : [
            "heartbeat-*"
          ],
          "query" : {
            "size" : 0,
            "query" : {
              "bool" : {
                "filter" : [
                  {
                    "match_all" : {
                      "boost" : 1.0
                    }
                  },
                  {
                    "match_phrase" : {
                      "monitor.status" : {
                        "query" : "down",
                        "slop" : 0,
                        "zero_terms_query" : "NONE",
                        "boost" : 1.0
                      }
                    }
                  },
                  {
                    "range" : {
                      "@timestamp" : {
                        "from" : "now-5m",
                        "to" : "now",
                        "include_lower" : true,
                        "include_upper" : true,
                        "format" : "strict_date_optional_time",
                        "boost" : 1.0
                      }
                    }
                  }
                ],
                "adjust_pure_negative" : true,
                "boost" : 1.0
              }
            },
            "_source" : {
              "includes" : [ ],
              "excludes" : [ ]
            },
            "stored_fields" : "*",
            "script_fields" : { },
            "aggregations" : {
              "2" : {
                "terms" : {
                  "field" : "url.domain",
                  "size" : 5,
                  "min_doc_count" : 1,
                  "shard_min_doc_count" : 0,
                  "show_term_doc_count_error" : false,
                  "order" : [
                    {
                      "_count" : "desc"
                    },
                    {
                      "_key" : "asc"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    ],
    "triggers" : [
      {
        "id" : "DSywEnUBS4IZmca8t6Dv",
        "name" : "Down servers",
        "severity" : "1",
        "condition" : {
          "script" : {
            "source" : "ctx.results[0].hits.total.value > 5",
            "lang" : "painless"
          }
        },
        "actions" : [
          {
            "id" : "DiywEnUBS4IZmca8t6Dv",
            "name" : "Notify Slack",
            "destination_id" : "PBqsEnUBLpZBpv_l3pUi",
            "message_template" : {
              "source" : """{{#ctx.results.0.aggregations.2.buckets}}
{{key}}:
   Down events: {{doc_count}}
{{/ctx.results.0.aggregations.2.buckets}}
""",
              "lang" : "mustache"
            },
            "throttle_enabled" : true,
            "subject_template" : {
              "source" : "There are down servers",
              "lang" : "mustache"
            },
            "throttle" : {
              "value" : 10,
              "unit" : "MINUTES"
            }
          }
        ]
      }
    ],
    "last_update_time" : 1604868444350
  }`
1. Post the code using the dev console, it works. 
3. Post the code using curl with
` curl -H 'Content-Type: application/json' -uadmin:admin -k -XPUT "https://myelastic:9200/_opendistro/_alerting/monitors/someid"  --data-binary @filename_with_code`
```{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[110:26] [script] failed to parse object"}],"type":"x_content_parse_exception","reason":"[110:26] [script] failed to parse object","caused_by":{"type":"json_parse_exception","reason":"Unexpected character ('\"' (code 34)): was expecting comma to separate Object entries\n at [Source: (org.elasticsearch.common.bytes.AbstractBytesReference$MarkSupportingStreamInputWrapper); line: 110, column: 29]"}},"status":400}```

**Expected behavior**
I should get the same response that I get in the console, which is a document creation with 200 status

**Desktop (please complete the following information):**
 - OS: Windows 10 with WSL for curl
 - Browser chrome
 - Version 86.0.4240.183 (Official Build) (64-bit)

**Additional context**

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/79
