### ISSUE TITLE
Add "index" as destination for monitor

### ISSUE THREAD

**Issue by agone1** [opendistro-for-elasticsearch/alerting#298]
**Is your feature request related to a problem? Please describe.**
I am using monitors to create new documents in target indices. Right now I use a "webhook destination", which makes POST calls to following url:
`http://<cluster_node>:<es_port>/<target_index>/_doc`
with a stringified json as text payload.
This cause many inconviniences:

1. I have to stringify JSON object, and than parse it back to object from text when indexing.
2. One cant make a POST call to _bulk endpoint. For some reasons such calls are being rejected with an error.

**Describe the solution you'd like**
During many tests I figured out, that there is a possibility to transform search results with painless scripting in monitor's conditoin section, so one can easily modify **ctx.results**'s elements, even adding new fields.

I suggest to create a new destination which will check for a certain field (array of objects, for example **docs**) in the last element of **ctx.results** array, and use its value to prepare a bulk payload.
Document **_index** value should be configured via destination params, and optionally could be configured in **docs** field.
Document **_id** value optionally could be configured in **docs** field.
If **docs** field exists and is not null monitor action will perform a **_bulk** call to elasticsearch cluster itself.

Example:
```
{
  "ctx.results": [
    {<search input results>},
    {
      "docs": [
        { "_id": "<optional>", "_index": "<optional>", "_source": {<document payload>}}
      ]
    }
  ]
} 
```

**Comment by abdalians** [comment]
how did you authenticate from the monitor to Elasticsearch? Authorization: Basic <base64_encoded_username:password> doesnt work for me..

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/81
