### ISSUE TITLE
[BUG] Action to post alert to webhook causes java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by ianadeem** [opendistro-for-elasticsearch/alerting#299]
**Describe the bug**
I have a few monitors with triggers that post to a webhook destination (configured through the UI with just the URL and all defaults kept as-is). The webhook expects a simple JSON and returns 200 OK with a content-length of 0. When I run the monitor (through the API), I get the following error:

```
  "trigger_results" : {
    "uS7x1nUBvYWyvkdZnPNW" : {
      "name" : "Test",
      "triggered" : true,
      "error" : null,
      "action_results" : {
        "ui7x1nUBvYWyvkdZnPNW" : {
          "id" : "ui7x1nUBvYWyvkdZnPNW",
          "name" : "Slack",
          "output" : { },
          "throttled" : false,
          "executionTime" : 1605630054745,
          "error" : "java.lang.IllegalArgumentException: Response is missing"
        }
      }
    }
  }
```

If I run the same monitor with the query parameter `?dryrun=true`, I don't get an error. On the monitor page in Kibana, the entire history is shown as a gray band (indicating the error state). All the alerts in the history are also shown as errors and cannot be ACK'd. The alerts are still sent, but an exception is thrown when the response is dealt with. When I configure two actions with the same webhook, only one is sent (but shows the aforementioned error) and the second one errors out with `Destination document with id 29bmwnUB5Q26TYduZwRR not found or source is empty`.

The trigger is set up as follows:

```
    "triggers" : [
      {
        "id" : "uS7x1nUBvYWyvkdZnPNW",
        "name" : "Test",
        "severity" : "3",
        "condition" : {
          "script" : {
            "source" : "true",
            "lang" : "painless"
          }
        },
        "actions" : [
          {
            "id" : "ui7x1nUBvYWyvkdZnPNW",
            "name" : "Slack",
            "destination_id" : "29bmwnUB5Q26TYduZwRR",
            "message_template" : {
              "source" : """
{
    "monitor": "{{ctx.monitor.name}}",
    "trigger": "{{ctx.trigger.name}}",
    "severity": "{{ctx.trigger.severity}}",
    "when": "{{ctx.periodEnd}}",
    "reason": "Reason",
    "details": "Details"
}
""",
              "lang" : "mustache"
            },
            "throttle_enabled" : false,
            "subject_template" : {
              "source" : "",
              "lang" : "mustache"
            }
          }
        ]
```

I don't think it matters, but for the record, the monitor is defined with an extraction query and a cron schedule.

**Other plugins installed**
I am running AWS Elasticsearch 7.4.

**To Reproduce**
1. Configure a simple webhook destination with a URL and default settings.
2. Configure a simple monitor with an action to post to the webhook (make sure the trigger always fires).
3. Invoke the monitor with `POST _opendistro/_alerting/monitors/<monitor-id>/_execute?dryrun=true` and `POST _opendistro/_alerting/monitors/<monitor-id>/_execute` and observe the difference.

**Expected behavior**
The POST request above should not cause a `java.lang.IllegalArgumentException`. When multiple actions are configured, all of them should work.

**Screenshots**
N/A

**Desktop**
 - OS: Ubuntu 18.04
 - Browser: Firefox 82.0.3

**Additional context**
The response returned by the webhook:
```
< HTTP/2 200 
< date: Tue, 17 Nov 2020 16:09:34 GMT
< server: Apache
< content-length: 0
< content-type: application/json; charset=utf-8
< other headers ...
< 
```

**Comment by momoguy2** [comment]
Saw the assignment for bug fix was removed, +1 on hoping its re-assigned and fix can come out.
Desire Elasticsearch Slack notifications in lieu of current Chime notifications.
Thx much.

**Comment by skkosuri-amzn** [comment]
We are looking into this.

**Comment by aseempuri** [comment]
+1 - looking forward for the fix of this issue.

**Comment by shupingliu** [comment]
+1, would love to have this fixed!

**Comment by ftianli-amzn** [comment]
Hi @ianadeem,
Thank you for describing the bug with detailed information, which makes us easier to investigate. 👍
I can reproduce the both errors.

For the first one, the error with message `java.lang.IllegalArgumentException: Response is missing` is also reported in a another issue https://github.com/opendistro-for-elasticsearch/alerting/issues/133, and the bug is fixed in version [1.11.0.1](https://github.com/opendistro-for-elasticsearch/alerting/releases/tag/v1.11.0.1) which seems was released on the same day as you posted the issue.

Please upgrade Alerting plugin to at least version 1.11.0.1, which is compatible with Elasticsearch 7.9.1.

For the second error `Destination document with id xxx not found or source is empty`, it doesn't appear in ODFE, so there is no plan to fix it here.

Besides, my response may not solve your problems as you are using AWS Elasticsearch Services, but unfortunately we don't support AWS Elasticsearch Services here.

**Comment by ianadeem** [comment]
Thanks @ftianli-amzn. I'll see if the latest AWS ES ships with ODFE >= 1.11.0.1.
IIRC, the second error was just a symptom of the first problem. Thanks for looking into this!

**Comment by dbbaughe** [comment]
Believe this has been resolved in previous bug fix by allowing the response to not have a body. If there is still an issue let us know.
