### ISSUE TITLE
Stop sending notification to one destination

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro-for-elasticsearch/alerting#30]
**Use case:** 
We are sending alert notification to multiple destinations. For some reason, we don't want to send notification to one destination any more. 

I see the destination can be deleted on "Destinations" page. But if the destination is in usage, it can't be deleted and will pop up such warning "Couldn't delete destination dest1. One or more monitors uses this destination."  As the message doesn't show which monitor is using the destination, I have to go through all of the triggers and delete the actions which are using the destination (currently, one action can only send notification to one destination, maybe we can enhance it to support multiple destinations in one action?).

**Suggestions:**
1.Show which monitor/trigger/action are using the destination
2.Just suspend one destination if the delete action is too heavy.

**Comment by mihirsoni** [comment]
we had backlog on the showing which monitor / trigger / actions uses the destination or allow them to control for the same page. 

The reason we don't want to have multiple destinations in one action is , we still want them to have capabilities to choose subject and message differently based on their need. (i.e slack , just a summary or in email detailed message).

**Comment by bellfrog** [comment]
@mihirsoni thanks for the explanation, that's good if we have backlog to show such information and add control from destination page.

If we just use the same subject and message to multiple destination, we have to define multiple actions with the same subject/message, which seems boring. Supporting multiple destination can also have the capability to set different subject/messages for different groups of destinations. Maybe this enhancement is not so urgent, but I think it's nice to have.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/32
