### ISSUE TITLE
[BUILD FAILED] - Output for cmd:Error opening zip file or JAR manifest missing JACOCOAGENT.jar

### ISSUE THREAD

**Issue by bard0x** [opendistro-for-elasticsearch/alerting#305]
I'm trying to compile the project (GitHub TAG V1.6.0.0) but the build failed. (It's the same if I trying to compile the latest version of the project)

**Describe the bug**
Build Failed: Output for cmd:Error opening zip file or JAR manifest missing : build/tmp/expandedArchives/org.jacoco.agent-0.8.6.jar_a26f6511a7813217be4cd6439d66563b/jacocoagent.jar

**Screenshots**
![image](https://user-images.githubusercontent.com/24570908/100435801-bd126f00-309e-11eb-8ccf-c91932543ec6.png)

**Desktop (please complete the following information):**
  Gradle Version    : 6.3
  OS Info               : Windows 10 10.0 (amd64)
  JDK Version        : 13 (Oracle JDK)

**Comment by diegobergamo** [comment]
Follow the issue.... same error for me, reproduced with mirror use-case ( repo cloned and opened with Intellij, java oracle JDK 15 + gradlew 6.7.1)

**Comment by lezzago** [comment]
Please use JDK 14 for the latest version of the plugin to be compiled correctly. Also please do not change the gradle version that is listed [here](https://github.com/opendistro-for-elasticsearch/alerting/blob/main/gradle/wrapper/gradle-wrapper.properties) for the plugin as that may require additional changes to work with that gradle version.

@bard0x it looks like you are using the incorrect gradle version for V1.6.0.0. The correct version should be 6.2.2 as seen [here](https://github.com/opendistro-for-elasticsearch/alerting/blob/v1.6.0.0/gradle/wrapper/gradle-wrapper.properties#L3).
