### ISSUE TITLE
Create Monitor- Multiple where clauses in Visual Graph option

### ISSUE THREAD

**Issue by taha2009** [opendistro-for-elasticsearch/alerting#307]
**Is your feature request related to a problem? Please describe.**
Currently while creating a monitor, while using visual graph option I can give a where clause, for our purposes we want user to be able to give more filters (Where clauses)

**Describe the solution you'd like**
Please provide option for user to create multiple where clauses (Filter)

**Describe alternatives you've considered**
For now we are planning to add a textarea where user can provide lucene queries for more detailed searches.

**Additional context**
N/A

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/83
