### ISSUE TITLE
Acknowledge alert for period of time 

### ISSUE THREAD

**Issue by ylwu-amzn** [opendistro-for-elasticsearch/alerting#31]
**Use case:**
I have received one alert notification and plan to work on it soon. So I just want to suppress the alert notification for next 4 hours. But currently acknowledge will suppress the notification totally. 

**Suggestion**
Enhance current acknowledge to support just acknowledge the alert for a period of time.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/33
