### ISSUE TITLE
[BUG] getMonitors throws illegal_argument_exception

### ISSUE THREAD

**Issue by dx034** [opendistro-for-elasticsearch/alerting#318]
**Describe the bug**
Calling `/api/alerting/alerts` either directly or via Kibana (by visiting the Alerts page) returns `[illegal_argument_exception] request [/_opendistro/_alerting/monitors/alerts] contains unrecognized parameters: [alertState], [searchString], [severityLevel], [size], [sortOrder], [sortString], [startIndex]`. Note that this happens both when these parameters are included in the call (as when called via Kibana) but also when they are omitted (tested using curl).
Alerts still work in Kibana, i.e. they trigger and get delivered to destinations but I cannot view alerts, destinations or monitors. 
I couldn't find any log output except for the error returned to the client. 

There was no update I'm aware of since this error occured. I'm using Kibana 7.9.1 with opendistro-alerting 1.11.0.2. 

**Other plugins installed**
All Opendistro plugins except for security.

**To Reproduce**
1. Open Kibana
2. Click on "Alerting"
3. It should now show a list of alerts. The error prevents this from happening.

**Expected behavior**
The call should not return an error.

**Desktop (please complete the following information):**
Tested via curl and Firefox.

**Additional context**
I already reinstalled the alerting plugin and removed bundles. Caches are all empty, both server-side and client-side. I ensured the plugin and Kibana are up-to-date and compatible.

**Comment by lezzago** [comment]
@dx034 I have tested with the ODFE 1.11 distribution for both Elasticsearch and Kibana and I am not seeing the error you have mentioned. I have also removed the security plugin from both Elasticsearch and Kibana. Which version of the ODFE Elasticsearch distribution and the alerting plugin (not the kibana one) are you using?

**Comment by dx034** [comment]
@lezzago I reinstalled all systems and restored from backups, it works again. It seems something was broken in the setup. Thanks for investigating.
