### ISSUE TITLE
Impossible to send message with Korean/Japanese on Action Message

### ISSUE THREAD

**Issue by lievel** [opendistro-for-elasticsearch/alerting#33]
I tried to send message with Korean/Japanese on Action Message("Send test message").
The Slack message was like this "?????" 
How do I send a message with the other language except English?

I tested with below docker images.
amazon/opendistro-for-elasticsearch:0.8.0
amazon/opendistro-for-elasticsearch-kibana:0.8.0

![스크린샷 2019-04-16 오후 2 55 04](https://user-images.githubusercontent.com/7918436/56186410-4146e880-605a-11e9-8e74-2890df655512.png)

![스크린샷 2019-04-16 오후 3 01 02](https://user-images.githubusercontent.com/7918436/56186373-296f6480-605a-11e9-8aba-3712a94f63f6.png)

**Comment by mihirsoni** [comment]
@lievel Thanks for reporting this I am able to reproduce the issue. 
we're missing passing encoding while constructing notification message.
