### ISSUE TITLE
Ability to configure notification on alert recovery

### ISSUE THREAD

**Issue by alfredolopezzz** [opendistro-for-elasticsearch/alerting#330]
**Is your feature request related to a problem? Please describe.**
We have to manually ACK and close ALL alerts that ODFE-alerting sends to us (we are using Opsgenie for routing alerts to on-call engineers) even if our systems manage to auto-heal correctly (ie, metrics go back to normal). This is not scalable when managing a system with lots of alerts.

**Describe the solution you'd like**
We would like to be able to receive notifications when a monitor "Trigger" transitions its status from "alert triggered" to "no alerts". Right now when creating a Trigger, in the "Configure actions" section, it is only possible to specify one single message which will be used to send a notification to the destination when *trigger enters the alert status*.

**Describe alternatives you've considered**
This is a showstopper for us, we are considering moving our observability platform out of ODFE.

**Comment by luiscarbajo23** [comment]
So interesting new feature!

**Comment by wpniederer** [comment]
Please add this, I'm in the same exact situation described by Alfredo and would appreciate having this functionality!

**Comment by steve-gale** [comment]
+1 for this

**Comment by sergey-onanchenko** [comment]
+1

**Comment by fiksm** [comment]
+1

**Comment by alfredolopezzz** [comment]
seems there more issues requesting this feature, ie: https://github.com/opendistro-for-elasticsearch/alerting/issues/28

**Comment by qreshi** [comment]
Closing in favor of the migrated issue https://github.com/opensearch-project/alerting/issues/87

Or more generically https://github.com/opensearch-project/alerting/issues/31

Please continue any further discussions in either of these.
