### ISSUE TITLE
Alert on anomaly with category-field - "No data to display" in trigger

### ISSUE THREAD

**Issue by NicoP-S** [opendistro-for-elasticsearch/alerting#332]
**Describe the bug**
If i try to add an alert to our anomaly detection with category field the alert trigger always says "No data to display".
The anomaly detector works. It's running and it  does find anomalies.
Opendistro version: 1.12.0

![grafik](https://user-images.githubusercontent.com/8988747/103514356-bda3df80-4e6c-11eb-8495-c485ebed31b0.png)

**To Reproduce**
1) Setup anomaly detector and add category-field
https://opendistro.github.io/for-elasticsearch-docs/docs/ad/#optional-set-a-category-field-for-high-cardinality
2) Add Alert for the detector 
3) the trigger always says no data
![grafik](https://user-images.githubusercontent.com/8988747/103514473-fe035d80-4e6c-11eb-9e36-59ae856c37ca.png)

I don't know if this is this a configuration problem on my side or a bug.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/88
