### ISSUE TITLE
Figure out how to expose domain model objects directly to mustache action scripts

### ISSUE THREAD

**Issue by ghost** [opendistro-for-elasticsearch/alerting#34]
Currently we can directly pass our domain model objects to the painless trigger scripts without converting them into an intermediate representation like Map<String, String>. This ensures that new fields are automatically available to trigger scripts when they're introduced.  

However due to the mustache script sandbox in ES we've been unable to do this for action templates scripts which means we need to manually convert domain models to String Maps.  This is inefficient and leads to issues like #26 . 

This issue is meant to investigate approaches to avoiding this conversion and exposing the domain model directly to action template scripts.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/34
