### ISSUE TITLE
Alerting types

### ISSUE THREAD

**Issue by tarekkilani** [opendistro-for-elasticsearch/alerting#350]
Hello, 

I'm new to OpenDistro and i found that we can send notifications using (Email / Slack / Custom webhooks)
I want to know if there is any way to send alerts to Jira or TheHive or any other ticketing system.

Thank you in advance.

**Comment by skkosuri-amzn** [comment]
Currently, there is no direct way of sending notifications to Jira or TheHive.
Please use [Open Distro forums](https://discuss.opendistrocommunity.dev/) for Q/A.
