### ISSUE TITLE
Problem with email alerts

### ISSUE THREAD

**Issue by tarekkilani** [opendistro-for-elasticsearch/alerting#351]
Hello, 

I'm trying to send notifications using email as destination but it doesn't work. The documentation is not clear...
I configured everything : senders, recipients and elasticsearch keystore and i don't get any notification. Notifications using slack are working properly but email notifications are not!
Please if i'm going to use gmail smtp server what is the configuration that i need to setup?
Are the "Email address" in the senders configuration and "./bin/elasticsearch-keystore add opendistro.alerting.destination.email.<sender_name>.username" the same?

**Comment by dutingda** [comment]
Hi, how have you resolved it?
