### ISSUE TITLE
email group updates not saved on Kibana

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [opendistro-for-elasticsearch/alerting#352]
**Describe the bug**
When email groups are updated with the kibana manage email groups feature, new email-addresses can be added and the changes can be saved. But using manage email groups again to confirm, the old settings are displayed. As well, using the api shows that the changes are not saved correctly. Managing the groups with the api works fine without problem. Thus it seems to be a Kibana issue.

**Other plugins installed**
No

**To Reproduce**
1. Go to Alerting / Destinations / Edit destinations / Manage email groups 
2. Expand group to edit
3. Add new entry to Emails
4. Click save
5. Kibana shows popup successfully saved
6. Open Manage email groups again
7. New entries are missing

**Expected behavior**
Properly updated group settings

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Browser [Edge, Chrome]
 - Version [Edge 87.0.664.75]

**Additional context**

**Comment by AWSHurneyt** [comment]
A fix for this issue has been merged into the `opendistro-for-elasticsearch/alerting-kibana-plugin` main branch.
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/pull/252

**Comment by gittygoo** [comment]
I'm stiill having this issue on opendistro 1.13.2.1
