### ISSUE TITLE
Alerting security exception

### ISSUE THREAD

**Issue by tarekkilani** [opendistro-for-elasticsearch/alerting#355]
Hello,

I have ELK stack + xpack installed then i installed Open Distro alerting module.
When i try to access Alerting page i get this error :

`[security_exception] action [indices:data/read/search] is unauthorized for user [_system]
`
Any help please?

**Comment by skkosuri-amzn** [comment]
Please consider using [Open Distro forum ](https://discuss.opendistrocommunity.dev/)for discussion and questions. Open Distro alerting is not supported with x-pack. This is covered in couple of forum threads and GitHub issues for more details.
