### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amar-mhatre** [opendistro-for-elasticsearch/alerting#356]
**Describe the bug**
A Monitor has raised an alert and it is active, if one restarts open-distro, multiple alerts are raised by trigger for same query and keeps generating.

**To Reproduce**
1. Create monitor trigger and action
2. Once an alert is generated and it is active state restart open-distro service
3.  After restarting one can see same monitor and trigger start generating multiple alerts every time monitor executes as per schedule all alerts are active and can be acknowledge separately.

**Expected behavior**
Even after restarting open-distro should maintain the state of an alerts, like it is maintaining before restarting

**Desktop (please complete the following information):**
 - OS: Debain
 - Version [Opendistro 6.7.1]

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/93
