### ISSUE TITLE
[BUG]"Propagate exception from publishing Email notifications to Action run result"

### ISSUE THREAD

**Issue by skkosuri-amzn** [opendistro-for-elasticsearch/alerting#359]
**Describe the bug**
Propagate exception from publishing Email notifications to Action run result

**To Reproduce**
1. Configure non-reachable email smtp server.
2. Configure and Trigger an alert.
3. Alert will show as Active even though it failed to send the email.

**Expected behavior**
1. Show alert status as Error and show error message.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/94
