### ISSUE TITLE
[BUG] Can not see monitors, destinations, email groups etc in GUI after installing through API

### ISSUE THREAD

**Issue by melkosoft** [opendistro-for-elasticsearch/alerting#366]
**Describe the bug**
I am trying to move alerting staff from one ES to another. The versions are the same - ODFE 1.11.0. I was able to extract alert data from source cluster using API (python script). When I add email accounts and email groups to new cluster using API I got message that they were added (got json with all correct data plus generated id) Going to kibana gui as user with admin rights - nothing in alerts are visible. Checking data using API - inserted data is there. If I run Dev Tools with the same API call - everything is visible from GUI. I am running API calls using "admin" account. What should I include in API call (any headers etc...) in order to have alerts visible. This is my command from script:
```
curl -k  -H "Content-Type: application/json" -H "Accept: application/json" -u admin:admin -X POST https://elasticsearch:9200/_opendistro/_alerting/destinations/email_groups -d '{"name": "example_email_group","emails": [{ "email": "example@email.com" }]}'
```
**Other plugins installed**
Please mention if you are using this plugin along side any other plugin. Security for example.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/97
