### ISSUE TITLE
ctx.alert.isAcknowledged not accessible with trigger

### ISSUE THREAD

**Issue by rini2208** [opendistro-for-elasticsearch/alerting#371]
IN openDistro kibana ctx.alert.isAcknowledged variable to accessible , giving error as
"caused_by" : {
    "type" : "illegal_argument_exception",
    "reason" : "field [com.amazon.opendistroforelasticsearch.alerting.model.Alert, isAcknowledged] not found"
  }

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/99
