### ISSUE TITLE
Feature Request: Kibana URL Link in Alerts

### ISSUE THREAD

**Issue by shreyu86** [opendistro-for-elasticsearch/alerting#38]
Thanks for the awesome work on the alerting plugin. I was curious if it would be feasible if the alerts generated have a link to Kibana dashboard for example here is an alert I have:
```
Monitor Free taco Monitor just entered alert status. Please investigate the issue.
- Trigger: Taco Parrot is Hungry
- Severity: 5
- Period start: 2019-04-25T18:32:14.670Z
- Period end: 2019-04-25T18:33:14.670Z
```
It will be great to include a link to the Kibana URL for the query in this monitor, alternatively if the link to the Monitor page is included that would be great to get some context around this alert and to ease triage process of the error.

**Comment by mihirsoni** [comment]
@shreyu86  Thanks for the request. 

Trying to understand more, so this is still possible by adding it as part of action message itself while creating the trigger and providing the monitor URL in action message. 

Are you suggesting to have this as default message or always append to the action message automatically ?

In case of appending always could cause some issues. Imagine, someone wants to use display monitor using some different way or one is using custom webhook. In that case user might want to send JSON in the message v/s just a text.

**Comment by shreyu86** [comment]
@mihirsoni Thanks for reply, can you please elaborate on how I go about providing the monitor URL in the message, is it attached to `ctx` or I hard code it from the Alerts app like `app/opendistro-alerting#/monitors/Z5YyE2oBvmugrp4G5caq`
> Trying to understand more, so this is still possible by adding it as part of action message itself while creating the trigger and providing the monitor URL in action message.

**Comment by mihirsoni** [comment]
@shreyu86  entire monitor object is available in `ctx`. so you can extract id from there. 

https://github.com/opendistro-for-elasticsearch/alerting/blob/1d730c0f2ebace04e2ad66f32e1130adbd73ceaa/alerting/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/model/Monitor.kt#L43-L50

Closing this for now, feel free to open this in case you face any other issue.

**Comment by shreyu86** [comment]
Great, thanks for the information @mihirsoni
