### ISSUE TITLE
0.9.0 is missing in debian/ubuntu repo 

### ISSUE THREAD

**Issue by skyrocknroll** [opendistro-for-elasticsearch/alerting#40]
apt-cache madison opendistroforelasticsearch
opendistroforelasticsearch |    0.8.0-1 | https://d3g5vo6xdbdb9a.cloudfront.net/apt stable/main amd64 Packages

**Comment by dbbaughe** [comment]
Hi @skyrocknroll,

Currently debian release only supports 0.8, but we're working on the 0.9 release.

**Comment by jinsoor-amzn** [comment]
Hi @skyrocknroll,

I  am happy tell you that we have announced Opendistro 0.9.0! Please read the following AWS Blog post.

https://aws.amazon.com/blogs/opensource/open-distro-for-elasticsearch-0-9-0-now-available/

**Comment by skyrocknroll** [comment]
@jinsoor-amzn Awesome :+1
