### ISSUE TITLE
Support for Alert Trigger Chaining

### ISSUE THREAD

**Issue by elfisher** [opendistro-for-elasticsearch/alerting#44]
A mechanism of chaining we should support is chaining triggers. The focus is to conditionally execute additional monitors/triggers based on based on previous trigger outcomes.

**Comment by dbbaughe** [comment]
Hey @elfisher,

Could you clarify what "previous trigger outcomes" means?
Are we talking about the previous outcome of the same trigger in the previous execution of the monitor?
Or TriggerB relies on the results of TriggerA when evaluating?

**Comment by elfisher** [comment]
@dbbaughe, I was thinking more along the lines of TriggerB relies on the outcome of TriggerA. This would enable workflows like where if TriggerA triggers then run queryB and check TriggerB.

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/37
