### ISSUE TITLE
i can not find elastic stack new features like Infrastructure 

### ISSUE THREAD

**Issue by ZMMWMY** [opendistro-for-elasticsearch/alerting#53]
like kibana Infrastructure,logs features ,did you remove it ?

**Comment by alolita** [comment]
Can you provide more details about your question?

**Comment by ZMMWMY** [comment]
This photo is taken from [demo.elastic.co](https://demo.elastic.co) screenshots.
i meant I can't find these features
![image](https://user-images.githubusercontent.com/19320021/57590852-e02f0980-7560-11e9-8462-1582b9ac4a1d.png)

**Comment by ZMMWMY** [comment]
i realized opendistro remove x-pack plugin ,that's why i could not find that

**Comment by mihirsoni** [comment]
Open Distro uses OSS distribution from Elastic so you would not get any x-pack features.

Closing this for now, feel free to open new issue incase you face any OD related issue.
