### ISSUE TITLE
How do I complete an alert?

### ISSUE THREAD

**Issue by jonseymour** [opendistro-for-elasticsearch/alerting#55]
I have created a monitor and trigger which as resulted in an alert being triggered.

In the UI I can acknowledge the alert. However, there doesn't appear to be a UI element that allows me to move the alert from the "Acknowledged" state to the "Completed" state which means that when new instances of the condition trigger, I do not receive a new alert.

How do I move the existing acknowledged alert into a completed state?

I am using the Open Distro For Elasticsearch which is packaged with AWS ElasticSearch v6.1.3.

**Comment by jonseymour** [comment]
Ok, form reading [this](https://discuss.opendistrocommunity.dev/t/alert-is-not-triggering/186/13) I discovered that the issue was that with an "Schedule by interval" monitor, Elasticsearch is not adding the interval boundaries to the query and that apparently I must interpolate them myself perhaps by using ctx.periodStart and ctx.periodEnd. The requirement to specify a time filter myself was contrary to my expectations as a user, but so be it.

The example in the forum post used hard coded interval boundaries in the monitor definitions, but I don't want to code the interval duration in two places - in the monitor source AND in the trigger definition. If I have to code the interval boundary in both places, then maintenance will almost certainly result in the redundant configuration being misconfigured in at least one place.

Can someone provide me with variable interpolation syntax for monitor definitions? I did try consulting Google, but didn't have much luck finding the correct incantation. Specifically, I want to use ctx.periodStart and ctx.periodEnd in the "from" and "to" attributes of the "@timestamp" "range" filter.

```
{
  "size": 0,
  "query": {
    "bool": {
      "must": {
        "query_string": {
          "query": "\"container wrapper: container starts...\"",
          "fields": [],
          "type": "best_fields",
          "default_operator": "or",
          "max_determinized_states": 10000,
          "enable_position_increments": true,
          "fuzziness": "AUTO",
          "fuzzy_prefix_length": 0,
          "fuzzy_max_expansions": 50,
          "phrase_slop": 0,
          "escape": false,
          "auto_generate_synonyms_phrase_query": true,
          "fuzzy_transpositions": true,
          "boost": 1
        }
      },
      "filter": [
        {
          "range": {
            "@timestamp": {
              "from": now-5m,
              "to": null,
              "include_lower": true,
              "include_upper": true,
              "boost": 1
            }
          }
        }
      ]
    }
  }
}
```

**Comment by mihirsoni** [comment]
@jonseymour Thanks for the detail info

For the query like this , you can use `{{period_start}}` and `{{period_end}}` and it will be substitute when the monitor is being run. 

Example query :
```
{
    "size": 0,
    "query": {
        "bool": {
            "filter": [
                {
                    "range": {
                        "order_date": {
                            "from": "{{period_end}}||-1h",
                            "to": "{{period_end}}",
                            "include_lower": true,
                            "include_upper": true,
                            "format": "epoch_millis",
                            "boost": 1
                        }
                    }
                }
            ],
            "adjust_pure_negative": true,
            "boost": 1
        }
    },
    "aggregations": {}
}
```

I think I would like to get this added in documentation.

**Comment by mihirsoni** [comment]
@jonseymour  I am closing this now assuming you're okay with solution. 

Feel free to re-open in case any other issues arise.
