### ISSUE TITLE
Support for GET _opendistro/_alerting/destinations in API

### ISSUE THREAD

**Issue by jonseymour** [opendistro-for-elasticsearch/alerting#56]
Currently the API lacks a way to discover the identifiers of existing destination definitions.

Two attempts to create a destination with exactly the same definition will result in duplicate definitions of the same destination being created with no way to reconcile the two definitions or do a preceding lookup to discover the identifier of an existing definition. 

To help prevent this occurring, it seems the user of the API must record the identifiers of all previously created destinations in some external scratch pad which seems a fragile solution at best.

**Comment by mihirsoni** [comment]
@jonseymour Thanks for the request. I've added this in our backlog to expose a REST endpoint.

for the workaround, you could use elasticsearch query on index `.opendistro-alerting-config` index and get all the monitors.

**Comment by skkosuri-amzn** [comment]
This is being tracked using: https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/issues/177

**Comment by phillbaker** [comment]
For tracking purposes, it seems like this was added in 1.11.0: https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/main/release-notes/opendistro-for-elasticsearch-release-notes-1.11.0.md#alerting-kibana-plugin, via: https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/pull/190
