### ISSUE TITLE
False positive alerts

### ISSUE THREAD

**Issue by Pupkur** [opendistro-for-elasticsearch/alerting#57]
I have alert like 
```
{
    "query": {
        "bool": {
            "must": [
                {
                    "query_string": {
                        "query": "*",
                        "fields": [],
                        "type": "best_fields",
                        "default_operator": "or",
                        "max_determinized_states": 10000,
                        "enable_position_increments": true,
                        "fuzziness": "AUTO",
                        "fuzzy_prefix_length": 0,
                        "fuzzy_max_expansions": 50,
                        "phrase_slop": 0,
                        "escape": false,
                        "auto_generate_synonyms_phrase_query": true,
                        "fuzzy_transpositions": true,
                        "boost": 1
                    }
                },
                {
                    "range": {
                        "@timestamp": {
                            "from": "now-5m",
                            "to": null,
                            "include_lower": true,
                            "include_upper": true,
                            "boost": 1
                        }
                    }
                }
            ],
            "adjust_pure_negative": true,
            "boost": 1
        }
    },
    "sort": [
        {
            "@timestamp": {
                "order": "desc"
            }
        }
    ]
}
```
I can see many logs in "Discovery" but I`m also have false positive messages about "All logs is missing"

Server works slowly because of 

elasticsearch log
![image](https://user-images.githubusercontent.com/40593634/57751800-89a40580-76ef-11e9-87a6-da26839745c1.png)

Do you use any kind of query response timeout in monitor? I think we should check query status (running \ failed \ completed) before sending alert.

**Comment by mihirsoni** [comment]
@Pupkur 
I am not sure if I understand correctly, but you're trying to say that the monitor is taking too much time to execute the query and trigger the alarm ? 

could you provide few more information, that  would be helpful to understand it better.

**Comment by Pupkur** [comment]
Yes. Monitor taking too much time to execute the query and trigger alarm.

**Comment by mihirsoni** [comment]
@Pupkur  Thanks for the information.

Could you check what is the query performance when you actually run the query ? 

You can do this by following steps :

1. Edit the existing monitor
2. Click on the Run button
3. Check the performance section ?

![Screen Shot 2019 05 15 at 1 23 23 AM](https://user-images.githubusercontent.com/578861/57760372-44141800-76b0-11e9-8989-ebcfd7690f2d.png)


**P.S** Also, make sure you're following best practices for the ES query as you're using `query_string` inside query, it is sometime too expensive. [Reference] I would sus(https://www.elastic.co/guide/en/elasticsearch/reference/6.7/query-dsl-query-string-query.html)

**Comment by Pupkur** [comment]
Query duration
6104-15840 ms

**Comment by dbbaughe** [comment]
Hi @Pupkur,

Just checking in if this was still an issue with newer version of the Alerting plugin?
We do have query timeouts on the input queries and if it does in fact timeout it will enter ERROR state which will automatically trigger the notification/alert.

**Comment by skkosuri-amzn** [comment]
Feel free to reopen, if this is still an issue.
