### ISSUE TITLE
Display the actual error/stack trace in Groovy/Painless script in UI while creation of triggers in Extraction query based alerts.

### ISSUE THREAD

**Issue by abhijithshivaswamy** [opendistro-for-elasticsearch/alerting#58]
While creating  a trigger, if there is a error in the painless/groovy script, only a error flag is shown "runtime error", the actual error/stack trace is not displayed, it would greatly improve the user experience if he can see the actual error when he runs the trigger while creating it.

**Comment by lucaswin-amzn** [comment]
+1 from me, what would also be great is if we could somehow integrate this with how the Elasticsearch DSL currently updates and informs you what the available params are and highlights any syntax errors.

**Comment by seraphjiang** [comment]
one option is to render full response just when we run esquery wtith syntax via Dev Tools

an example response will be like below.

```
{
  "type" : "script_exception",
  "reason" : "compile error",
  "script_stack" : [
    "... [0].hits.total.value > 0\nctx.results[0].hits.total ...",
    "                             ^---- HERE"
  ],
  "script" : "ctx.results[0].hits.total.value > 0\nctx.results[0].hits.total.value > 0\nctx.results[0].hits.total.value > 0\n",
  "lang" : "painless",
  "caused_by" : {
    "type" : "illegal_argument_exception",
    "reason" : "unexpected token ['ctx'] was expecting one of [{<EOF>, ';'}]."
  }
}
```
