### ISSUE TITLE
Add support for Cross-cluster search (CCS)

### ISSUE THREAD

**Issue by tomerilp** [opendistro-for-elasticsearch/alerting#62]
Hello,

Do you have any plan to support [CCS](https://www.elastic.co/guide/en/kibana/master/management-cross-cluster-search.html)?

I have a use case when we use a centralized CCS cluster which holds no data but connects to remote clusters and serves as a proxy.
I'd like to create alerts on the same way we search, this is in order to eliminate the need for duplicate and maintain the same alerts xN times.
 
Currently, the Alert plugin for Kibana only shows the local indices and doesn't expose any remote indices.
As far as I know, Elasticsearch does not support the retrieving of remote cluster's indices from CCS, therefore I was thought about fetching this information from Kibana's [Saved Objects API](https://www.elastic.co/guide/en/kibana/master/saved-objects-api.html).

WDYT?

**Comment by lucaswin-amzn** [comment]
Hi @tomerilp,
While I don't think this is exactly cross cluster, we are currently starting efforts on implementing issue #47 in a way such that you can perform operations to other endpoints, which could be another Elasticsearch domain.

Is this somewhat what you are looking for?

**Comment by tomerilp** [comment]
> Hi @tomerilp,
> While I don't think this is exactly cross cluster, we are currently starting efforts on implementing issue #47 in a way such that you can perform operations to other endpoints, which could be another Elasticsearch domain.
> 
> Is this somewhat what you are looking for?

Might be, but in my opinion, CCS should be natively supported rather than adding it explicitly.
We could get this information directly from Kibana

**Comment by dbbaughe** [comment]
Hi @tomerilp,

Was this still an issue? I see you asked in the other GitHub issue if Alerting was fixed by the security change. Wondering if this is something we need to change in one of the Alerting plugins or if the security plugin was causing the issue.

**Comment by tomerilp** [comment]
Hi @dbbaughe,

It is not related to the security plugin.
My scenario is we have 1 centralized cluster which connected to many downstream clusters with CCS. That centralized cluster holds no data, just serves as a user-facing Kibana for visualizations, searches in a centralized way.

What I wanted to have is the same experience with the Alerting system. A centralized way to create my alerts against all the downstream clusters. This way the user won't have to go to each cluster and create the same alert.

The alerting configurations should exist in the centralized cluster and search against remote clusters data.

WDYT is this feasible?

**Comment by tomerilp** [comment]
Hi @dbbaughe,

You right! I can confirm that the CCS alerts work when creating them using the API.
Would it possible to support it within the UI?

**Comment by dbbaughe** [comment]
Yes, should be possible to support in the UI. Will close this in favor of the other issue you made on the Kibana repository.
