### ISSUE TITLE
If opendistro for ELK 7.x

### ISSUE THREAD

**Issue by yangcaixing** [opendistro-for-elasticsearch/alerting#66]
Hi all, 
   I see now the opendistro v0.9.0 only support to ELK 6.7.1, and with the ELK 7.x.x Released, it seems that opendistro was incompatible with new ELK, so if you consider to update the version compatible with ELK 7.x.x, thanks in advance .

**Comment by japel** [comment]
seems like support was merged to master:
https://github.com/opendistro-for-elasticsearch/alerting/pull/41
but there is still no release

**Comment by lucaswin-amzn** [comment]
Release 7.X has been made public:
[ES 7.0 Release](https://github.com/opendistro-for-elasticsearch/alerting/releases/tag/v1.0.0.0)
