### ISSUE TITLE
Opendistro configuration support

### ISSUE THREAD

**Issue by yangcaixing** [opendistro-for-elasticsearch/alerting#76]
Hi all,
I use elastiflow to monitor network traffic, and I'm stuck in the opendistro configure, I want to use opendistro to trigger alert, for example when the client IP total traffic exceed 1GB in last 15 min, opendistro will trigger an alert via email or webhook. but now I don't know opendistro how to get the index data, and how to configure condition when client traffic sum exceed 1GB, here is my index templet, I need the filed "flow"{"bytes:", "client_hostname":},hope someone can help me, thanks in advance.
```
{
	"_index": "elastiflow-3.4.1-2019.06.13",
	"_type": "doc",
	"_id": "XjDTTmsBwJmiCTy6dE1w",
	"_version": 1,
	"_score": null,
	"_source": {
		"@Version": "3.4.1",
		"event": {
			"host": "10.10.101.1",
			"type": "netflow"
		},
		"node": {
			"ipaddr": "10.10.101.1",
			"hostname": "10.10.101.1"
		},
		"flow": {
			"tos": 20,
			"src_hostname": "172.217.24.206",
			"input_snmp": 24,
			"client_autonomous_system": "private",
			"ip_version": "IPv4",
			"server_hostname": "172.217.24.206",
			"bytes": 2917,
			"dst_mask_len": 23,
			"dst_port": 60813,
			"server_autonomous_system": "Google LLC (15169)",
			"client_hostname": "10.213.221.184",
			"dst_addr": "10.213.221.184",
			"src_country_code": "US",
			"sampling_interval": 0,
			"traffic_locality": "public",
			"src_geo_location": {
				"lon": -97.822,
				"lat": 37.751
			},
			"output_ifname": "index: 3",
			"autonomous_system": "Google LLC (15169)",
			"service_port": "443",
			"src_port_name": "https (TCP/443)",
			"service_name": "https (TCP/443)",
			"server_geo_location": "37.751,-97.822",
			"country_code": "US",
			"server_country": "United States",
			"dst_port_name": "TCP/60813",
			"dst_hostname": "10.213.221.184",
			"ip_protocol": "TCP",
			"input_ifname": "index: 24",
			"dst_autonomous_system": "private",
			"src_addr": "172.217.24.206",
			"server_asn": "15169",
			"application": "Google Docs/Drive",
			"client_addr": "10.213.221.184",
			"src_mask_len": 0,
			"src_country": "United States",
			"server_country_code": "US",
			"src_port": 443,
			"src_autonomous_system": "Google LLC (15169)",
			"packets": 31,
			"country": "United States",
			"server_addr": "172.217.24.206",
			"src_asn": 15169,
			"direction": "unspecified",
			"output_snmp": 3
		},
		"@timestamp": "2019-06-13T03:13:28.000Z",
		"netflow": {
			"first_switched": "2019-06-13T03:12:28.999Z",
			"in_bytes": 2917,
			"version": 9,
			"flowset_id": 289,
			"ipv4_dst_prefix": "10.213.220.0",
			"flow_seq_num": 4902055,
			"last_switched": "2019-06-13T03:13:20.999Z",
			"in_pkts": 31
		}
	},
	"fields": {
		"netflow.first_switched": [
			"2019-06-13T03:12:28.999Z"
		],
		"@timestamp": [
			"2019-06-13T03:13:28.000Z"
		],
		"netflow.last_switched": [
			"2019-06-13T03:13:20.999Z"
		]
	},
	"sort": [
		1560395608000
	]
}
```

**Comment by mihirsoni** [comment]
Hi @yangcaixing 

Trying to understand on your use case , You want to aggregate for a given time period with all **IP addresses** and sum of all **bytes.**  or just want to filter on specific host or static IP ? If you just want to monitor a single **client_host** you can create monitor using below query and modify with adding filter for client_host. If you want to get notified on if any of the client_host breaches threshold then you can create a monitor using sample query and write a Trigger in painless script.

Here is a sample query that you could you use as part of the creating a monitor using extraction query.You should modify below sample query as per your need adjust filters and apply time rage as necessary.  This query will give you list of **client_host** with their **sum(bytes)**

```
{
  "size": 0, 
  "aggs": {
    "client_host": {
      "terms": {
        "field": "flow.client_hostname"
      },
      "aggs": {
       "byes":  {
          "sum": {
             "field": "flow.bytes"
          }
       }
      }
    }
  }
}
```

**Comment by yangcaixing** [comment]
Hi @mihirsoni, 
   Thank very much, because my flow index are very huge, I want calculate all the IP ,and the sum bytes of each IP. when any client_host traffic breaches threshold, such as 1GB, I want trigger an alert as below:  
IP:172.20.132.196, bytes: 2GB
IP:172.20.110.24, bytes: 3GB.
I try your query example, now I can get the IP and it's bytes info, but how to I write the trigger condition query, to monitor each IP and it's traffic, if meet the condition, will trigger the action, would you pleas help to me,  thanks in advance. 
![open1](https://user-images.githubusercontent.com/41502299/60693463-f2984480-9f0c-11e9-8e66-423facc50582.png)
![2](https://user-images.githubusercontent.com/41502299/60693468-f75cf880-9f0c-11e9-8150-44cc0df067d2.png)
![3](https://user-images.githubusercontent.com/41502299/60693494-1b203e80-9f0d-11e9-996c-4a3bc3b8ca07.png)

**Comment by yangcaixing** [comment]
Hi @mihirsoni 
And bellow are the query results, I paste the whole field, I already sorted the buckets as bytes "desc", so could you pleas help me, how to write the trigger condition for this buckets, and how to extract the "key" and "value" to action notification, I'm new to opendistro, thanks very much.
    "_shards": {
        "total": 25,
        "failed": 0,
        "successful": 25,
        "skipped": 0
    },
    "hits": {
        "hits": [],
        "total": {
            "value": 10000,
            "relation": "gte"
        },
        "max_score": null
    },
    "took": 72,
    "timed_out": false,
    "aggregations": {
        "client_host": {
            "doc_count_error_upper_bound": -1,
            "sum_other_doc_count": 977161,
            "buckets": [
                {
                    "doc_count": 12544,
                    "bytes": {
                        "value": 1949235700
                    },
                    "key": "172.20.120.104"
                },
                {
                    "doc_count": 697,
                    "bytes": {
                        "value": 1856866682
                    },
                    "key": "172.20.150.82"
                },
                {
                    "doc_count": 1960,
                    "bytes": {
                        "value": 1683565579
                    },
                    "key": "172.20.120.151"
                },
                {
                    "doc_count": 865,
                    "bytes": {
                        "value": 1091118606
                    },
                    "key": "172.20.144.81"
                },
                {
                    "doc_count": 1469,
                    "bytes": {
                        "value": 1032784474
                    },
                    "key": "172.20.150.67"
                },
                {
                    "doc_count": 92,
                    "bytes": {
                        "value": 830436284
                    },
                    "key": "172.20.60.14"
                },
                {
                    "doc_count": 1126,
                    "bytes": {
                        "value": 696536181
                    },
                    "key": "172.20.170.67"
                },
                {
                    "doc_count": 1111,
                    "bytes": {
                        "value": 577392383
                    },
                    "key": "10.10.101.2"
                },
                {
                    "doc_count": 1379,
                    "bytes": {
                        "value": 522637517
                    },
                    "key": "172.20.80.27"
                },
                {
                    "doc_count": 580,
                    "bytes": {
                        "value": 459864599
                    },
                    "key": "172.20.80.82"
                }
            ]
        }
    }
}

**Comment by mihirsoni** [comment]
Hi @yangcaixing 

To solve your problem, you can modify query in a such way that would give you buckets only if they're breaching threshold using [bucket_selector](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/search-aggregations-pipeline-bucket-selector-aggregation.html) aggregation in Elasticsearch.

Sample Query

```
{
  "size": 0, 
  "aggs": {
    "client_host": {
      "terms": {
        "field": "flow.client_hostname"
      },
      "aggs": {
       "total_byes":  {
          "sum": {
             "field": "flow.bytes"
          }
       },
       "bytes_bucket_filter": {
          "bucket_selector": {
            "buckets_path": {
              "totalBytes":"total_bytes"
            },
            "script": "params.totalBytes > 300"
          }
        }
      }
    }
  }
}
```
Above query will result buckets of client_host only if they're breaching threshold mentioned inside script otherwise it will be empty. Now you can write simple trigger condition on length of buckets, if it is more than 0 that means there are client_hosts who is breaching threshold and then can be printed in your action message. For more details on how to please refer [documentation](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/#extraction-query).

**P.S :** Please ensure the performance of query and tune it accordingly.

I am closing this issue for now, feel free to re-open / create new issue if you find any bugs. I would suggest to use official [forum](https://discuss.opendistrocommunity.dev/) for questions instead of using Github. This will help us to manage our Github strictly for issues and feature requests.
