### ISSUE TITLE
Deleted monitors keep executing a queries

### ISSUE THREAD

**Issue by Czechh** [opendistro-for-elasticsearch/alerting#84]
I created a monitor in the cluster and proceded to delete it. After deletion I verified in my instrumentation the there was still a query running on a schedule, so I verified via curl `/_opendistro/_alerting/stats` and the deleted `id` still shows up
```
...
		"kmCLAWwB22FWnZ-IG6_Y": {
          "last_execution_time": 1563541589590,
          "running_on_time": true
        },
...
```

But the monitor reference seems to not exist anymore. If I try to `GET` it no response comes back, I've also tried to execute it and I'm getting the following back:

```
{
  "message" : "Can't find monitor with id: kmCLAWwB22FWnZ-IG6_Y"
}
```

How can I make sure I delete this job and stop it from querying?

**Comment by dbbaughe** [comment]
Hi @Czechh,

Are you able to reproduce this issue?
Can you give a detailed list of steps you did (i.e. which APIs you called in what order) to reach this problem?

In the meantime, could you do an elasticsearch match_all query against the `.opendistro-alerting-config` index and verify that the monitor is not in the index.

Thanks!

**Comment by ylwu-amzn** [comment]
BTW, please list which version you are using

**Comment by Czechh** [comment]
Hi @dbbaughe and @ylwu-amzn !

Thank you for responses. For more context, I'm using AWS elasticsearch service, Elasticsearch Version 6.4.
```
...
"number" : "6.4.2",
"lucene_version" : "7.4.0",
...
```

Order of operations are:
0 - POST via api using `/_opendistro/_alerting/monitors`
1 - GET via api using `/_opendistro/_alerting/monitors/:id` to verify
2 - curl Stats `_opendistro/_alerting/stats` and I verify that the monitor is working.
  ```
  {
    "xcylFmwBrCdeo3nXj0ov": {
      "last_execution_time": 1563749244584,
      "running_on_time": true
    }
  }
  ```
3 - Then with the respective `id` I DELETE `/_opendistro/_alerting/monitors/:id`
4 - GET via api using `/_opendistro/_alerting/monitors/:id` to verify
  => 404
5 - Search via `match_all` and I also verified with:
```
curl -X GET ".../_opendistro/_alerting/monitors/_search?pretty" -H 'Content-Type: application/json' -d'
{
    "query" : {
        "term" : {
          "_id": "xcylFmwBrCdeo3nXj0ov"
        }
    }
}
'
```
Also tried searching dirrectly in the `.opendistro-alerting-config` index.

6 - Then when I verify stats (`_opendistro/_alerting/stats`) - I still see the monitor there:
```
{
  "xcylFmwBrCdeo3nXj0ov": {
    "last_execution_time": 1563749844584,
    "running_on_time": true
  }
```
7 - waited for multiple cycles (created it to run every 10 minutes and waited > 45 minutes)
```
{
  "xcylFmwBrCdeo3nXj0ov": {
    "last_execution_time": 1563752244584,
    "running_on_time": true
  }
}

```

I can verify with my instrumentation that the cluster is receiving queries and these only stop until I delete the whole index `.opendistro-alerting-config`. And as you can see the `stats` endpoint keep updating the monitor `id`. Not sure what is going on.

**Comment by dbbaughe** [comment]
Hi @Czechh,

Was able to replicate and we're looking into this, thanks for opening the issue.

**Comment by dbbaughe** [comment]
Hey @Czechh,

It seems that Alerting is currently disabled by default for 6.4, and the reason why it was able to schedule was a separate issue. Please reach out through AWS support to enable Alerting after which everything should be working correctly.

Thanks!
