### ISSUE TITLE
Unable to update the cluster settings to disable alerting

### ISSUE THREAD

**Issue by Czechh** [opendistro-for-elasticsearch/alerting#85]
Currently trying to disable the monitors via the cluster settings following your documentation.

```
curl -X PUT ".../_cluster/settings" -H 'Content-Type: application/json' -d'
> {
>     "persistent" : {
>         "opendistro.alerting.enabled" : "false"
>     }
> }
> '
```

I've tried using a `cluster.` prefix to the setting. Not sure what I'm missing.

**Comment by dbbaughe** [comment]
Hi @Czechh,

It seems the documentation does not match our actual code in this case.
https://github.com/opendistro-for-elasticsearch/alerting/blob/master/core/src/main/kotlin/com/amazon/opendistroforelasticsearch/alerting/core/settings/ScheduledJobSettings.kt#L29

Please use `opendistro.scheduled_jobs.enabled` instead.

**Comment by dbbaughe** [comment]
Opened issue in docs repo, closing this one.
