### ISSUE TITLE
Add Amazon SNS destination in Alerting

### ISSUE THREAD

**Issue by monitoringit** [opendistro-for-elasticsearch/alerting#91]
Is there a way to build Amazon SNS destination in opendistro Alerting?

Amazon SNS destination is available in Aws elasticsearch service but when we install opendistro plugin in self hosted elasticsearch i only see amazon chime, custom webhook and slack as the only options available? I am using 6.7.1 elasticsearch.

**Comment by dbbaughe** [comment]
Hi @monitoringit,

Currently we do not support Amazon SNS destination in Open Distro version. We need to create an Open Distro friendly implementation of Amazon SNS destination.

We can keep this open to track progress and future requests of this destination.

Thanks,
Drew

**Comment by monitoringit** [comment]
Thanks Drew!
Is that something i can build custom into my stack? I really like amazon
sns and would love to add it in opendistro as destination. Any pointers
will be helpful.

Also, can custom webhook to be used to send messages to amazon sns? If yes,
do you have any snippets of that config?

**Comment by qreshi** [comment]
Closing in favor of https://github.com/opensearch-project/alerting/issues/45
