### ISSUE TITLE
Customer Webhook Error Logging

### ISSUE THREAD

**Issue by nickmkk** [opendistro-for-elasticsearch/alerting#96]
I'm attempting to configure a custom webhook that's not working.  I'm hoping to view the error logs to see what's failing but it's not clear to me where they are stored.  Where should I be looking for these logs?

https://github.com/opendistro-for-
elasticsearch/alerting/blob/0400ba67bcc05140a65f33dc5eb0f09a5d805ea6/notification/src/main/java/com/amazon/opendistroforelasticsearch/alerting/destination/factory/CustomWebhookDestinationFactory.java#L45

Thanks in advance

**Comment by lucaswin-amzn** [comment]
Logs are being stored in the `elasticsearch.log` similar to regular elasticsearch logging for requests for example.
