### ISSUE TITLE
Error 500 when creating monitor

### ISSUE THREAD

**Issue by nerddelphi** [opendistro-for-elasticsearch/alerting#98]
Hi.

I'm getting a 500 error in Kibana when I try to create a monitor:

`   '{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"settings.get(\\"http.port\\") must not be null"}],"type":"illegal_state_exception","reason":"settings.get(\\"http.port\\") must not be null"},"status":500}',
Alerting - MonitorService - createMonitor: { [illegal_state_exception] settings.get("http.port") must not be null :: {"path":"/_opendistro/_alerting/monitors?refresh=wait_for","query":{},"body":"{\"name\":\"testeevents\",\"type\":\"monitor\",\"enabled\":true,\"schedule\":{\"cron\":{\"expression\":\"0 0 * * *\",\"timezone\":\"America/Sao_Paulo\"}},\"inputs\":[{\"search\":{\"indices\":[\"metricbeat-k8s-*\"],\"query\":{\"size\":0,\"aggregations\":{\"when\":{\"max\":{\"field\":\"kubernetes.event.count\"}}},\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":\"{{period_end}}||-1h\",\"lte\":\"{{period_end}}\",\"format\":\"epoch_millis\"}}}]}}}}}],\"triggers\":[],\"ui_metadata\":{\"schedule\":{\"timezone\":\"America/Sao_Paulo\",\"frequency\":\"daily\",\"period\":{\"interval\":1,\"unit\":\"MINUTES\"},\"daily\":0,\"weekly\":{\"mon\":false,\"tue\":false,\"wed\":false,\"thur\":false,\"fri\":false,\"sat\":false,\"sun\":false},\"monthly\":{\"type\":\"day\",\"day\":1},\"cronExpression\":\"0 */1 * * *\"},\"search\":{\"searchType\":\"graph\",\"aggregationType\":\"max\",\"timeField\":\"@timestamp\",\"fieldName\":\"kubernetes.event.count\",\"overDocuments\":\"all documents\",\"groupedOverTop\":5,\"groupedOverFieldName\":\"bytes\",\"bucketValue\":1,\"bucketUnitOfTime\":\"h\",\"where\":{\"fieldName\":[],\"operator\":\"is\",\"fieldValue\":0,\"fieldRangeStart\":0,\"fieldRangeEnd\":0}}}}","statusCode":500,"response":"{\"error\":{\"root_cause\":[{\"type\":\"illegal_state_exception\",\"reason\":\"settings.get(\\\"http.port\\\") must not be null\"}],\"type\":\"illegal_state_exception\",\"reason\":\"settings.get(\\\"http.port\\\") must not be null\"},\"status\":500}"}
  status: 500,
     status: 500 },
  statusCode: 500,
   '{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"settings.get(\\"http.port\\") must not be null"}],"type":"illegal_state_exception","reason":"settings.get(\\"http.port\\") must not be null"},"status":500}',`

It's weird once it returns a "http.port" setting.

**Comment by dbbaughe** [comment]
I believe this was because of the HttpInput being merged before the equivalent Kibana Alerting PR was merged. Assuming this is fixed, feel free to reopen if it's still an issue.
